### ISSUE TITLE
AppPool

### ISSUE THREAD

**Issue by deskpal** [nvisionative/nvQuickSite#100]
Hi David,

First of all congrats on the great App! Really a great service to DNN and the community!

Problem I had when I tried: I have chosen a new AppPool for a DNN 8.0.1 install and the appPool was setup as .NET 2.0 - Maybe because this is the default on IIS, but it should have been setup with .NET 4

That's it for now!

Cheers,
Aderson

**Comment by nvisionative** [comment]
Thanks for the kudos and for posting this issue @deskpal.  We believe you are correct in your assumption, but we'll do some testing and see what we can come up with.  How do you think this should work?

**Comment by deskpal** [comment]
Don't want to over-complicate, but you asked:)

It should be established whether or not the system has the minimum requirements to run that selected version of DNN. This would include the minimum SQL version as well and the minimum .NET framework version. 

With that in hand, the app should try to assign the proper .NET framework version when creating a new AppPool. If the minimum framework is not available, well, you might point the user to download it (or automate its installation as well - maybe asking too much :)

If the minimum or any subsequent versions are available, then have it set. I would assume (big assumption) that when the code is creating the AppPool it should allow you to set the .NET framework version.

Sorry, longer than I thought!

**Comment by nvisionative** [comment]
@deskpal thanks for the insight on how you would like to see this work.  There are several challenges with this that will need to be worked through.  If you have thoughts on these, let us know.  

(By the way, currently nvQuickSite uses the default framework for IIS when creating a new site.)

- We would need a definitive list of valid .NET Framework versions for all DNN versions 6.2.0+.  I'm sure we can find this.  ;-)
- We would need to determine the default to set for the AppPool based on the version of DNN.  Would this be the min or max .NET Framework based on the list above?
- We would need to determine all installed .NET Framework versions installed.
- We would most likely need to provide a way for the user to override the .NET Framework being associated with the AppPool being created.  This selection would most likely be derived from the list generated from the previous bullet list item.
- We would need to figure out a mechanism to, at minimum, point users to where they can download/install other .NET Frameworks.

All that said, one of the benefits to nvQuickSite is the simple UI/UX.  To open this functionality will provide some nice features.  However, we need to balance that with keeping things simple.

**Comment by deskpal** [comment]
@nvisionative - Correct, this should not over complicate the application UI, and I think it wouldn't. Most of that could be defaults and hidden from the user's main experience with, maybe, a panel that would show up in case they want to explore "other options" or "advanced options"

**Comment by nvisionative** [comment]
@deskpal we will take a look into this more closely.  Thank you again for your input!

**Comment by abukres** [comment]
The fix for the  apppool .NET version is in the PR for issue #140. As for the DNN minimum .NET version, this can be added in the PackageManifest.xml file as a new property and there's a value for each DNN version.
