### ISSUE TITLE
Create Database Error, while in Windows Auth mode

### ISSUE THREAD

**Issue by bhattjidotcom** [nvisionative/nvQuickSite#101]
![createdatabasedeniedinmaster](https://cloud.githubusercontent.com/assets/10000502/14103398/94d59272-f5bd-11e5-8052-121b9b5aaad6.png)

Create Database Error, while in Windows Auth mode

**Comment by nvisionative** [comment]
@bhattjidotcom as stated before, we have not been able to reproduce this issue.  If you are getting this on your custom version of the application, I'm afraid we will not be able to support it.  If you are getting this on our released version, we'll be more than happy to help you if you can supply the exact steps to reproduce the issue.  Thanks.

**Comment by bhattjidotcom** [comment]
This is not on my custom version, it is on the standard version that I have downloaded.

As I have stated, the App gives error when trying Windows Auth. My guess, is some entries might be required in the master database so that it can accept the "IIS AppPool\Custom-App-Pool" as dbowner (I am not sure though)

I have installed fresh Windows 10, and enabled IIS with ALL features. I have installed Sql Server 2014 Express. Hope that will help

**Comment by nvisionative** [comment]
@bhattjidotcom thank you for the clarification.  nvQuickSite accesses the master database using Windows Authentication if selected.  If not, it uses the credentials entered.  If neither have the appropriate level of permissions in your local MSSQL Server instance, then you will see the error you have shared.  Please try connecting to the master database via SSMS directly (using Windows Authentication) and see what happens then.  Thanks.

**Comment by bhattjidotcom** [comment]
I am able to connect to SSMS using Windows Auth directly, no issue there

But still getting the above error on Windows 10

**Comment by nvisionative** [comment]
@bhattjidotcom we have been unable to reproduce this behavior and believe it is a local database configuration issue rather than an issue with this app.
