### ISSUE TITLE
Require Branding by CompanyID

### ISSUE THREAD

**Issue by bhattjidotcom** [nvisionative/nvQuickSite#102]
The AppPool that gets created is ending with "_nvQuickSite" 
Needs this to be overridden. I have put a CompanyID text box and tried, the Application gets compiled fine, but gives various errors (redirection.config can't be loaded etc)

Can you put a text box say txtCompanyID and let the user brand his CompanyID?

![brandingbycompanyid](https://cloud.githubusercontent.com/assets/10000502/14103671/d7a30b60-f5be-11e5-9f87-86bbe5dc1777.png)

**Comment by nvisionative** [comment]
@bhattjidotcom - thanks for your feedback and recommendations.  However, this is not a change we will be making at this time.
