### ISSUE TITLE
I am getting error after compiling 

### ISSUE THREAD

**Issue by bhattjidotcom** [nvisionative/nvQuickSite#103]
I am getting error after compiling myself. The App got compiled fine, but when run it gives error
![erroraftercompiledapp](https://cloud.githubusercontent.com/assets/10000502/14103909/ef22cfe0-f5bf-11e5-908d-265268f590d3.png)

**Comment by nvisionative** [comment]
@bhattjidotcom - we are unable to support issues with customized versions of this application.

**Comment by bhattjidotcom** [comment]
Well, I am getting errors.

I merely downloaded the source, rebuild the solutions, added missing Metro dlls, once again recompiled. It went successful this time.

I copied the .exe file to C:\Program Files (x86)\nvisionative\nvQuickSite and got the error

![erroraftercompiling](https://cloud.githubusercontent.com/assets/10000502/14140391/49f281f0-f696-11e5-8482-6e12b502ce31.png)

**Comment by nvisionative** [comment]
Please see response to #104
