### ISSUE TITLE
Error after mere recompilation of source

### ISSUE THREAD

**Issue by bhattjidotcom** [nvisionative/nvQuickSite#104]
Well, I am getting errors.

I merely downloaded the source, rebuild the solutions, added missing Metro dlls, once again recompiled. It went successful this time.

I copied the .exe file to C:\Program Files (x86)\nvisionative\nvQuickSite and got the error

![erroraftercompiling](https://cloud.githubusercontent.com/assets/10000502/14140391/49f281f0-f696-11e5-8482-6e12b502ce31.png)

**Comment by hismightiness** [comment]
I'd suggest doing a quick Jing video or something to illustrate what's happening to you since you appear to be the only one that's experiencing this issue.  It might help to illustrate something that's not getting articulated.

**Comment by nvisionative** [comment]
@bhattjidotcom - the are many factors that can cause errors when you choose not to use the [release version of the app](https://github.com/nvisionative/nvQuickSite/releases/download/v1.0.1/nvQuickSite_v1.0.1_Installer.msi). Can you please try installing and running the release version of the app? Do you get the same error then?.

**Comment by bhattjidotcom** [comment]
ok, I will create a video

**Comment by nvisionative** [comment]
@bhattjidotcom do you have the video?
