### ISSUE TITLE
Autogenerate database name based on site name

### ISSUE THREAD

**Issue by jbrinkman** [nvisionative/nvQuickSite#106]
When creating websites, it would be nice to have all aspects of the websites use a common name.  For example: if I choose to name my site xyz.dnndev.me, then make the installer smart enough to suggest a database name with the xyz name.

**Comment by nvisionative** [comment]
Thank you for the suggestion @jbrinkman.  We are interested in hearing what others think of this.  In initial interviews we conducted, everyone preferred to just have the app remember their last used DB name, since many of them utilize a specific naming convention (that is sometimes not based on the site name).  We are open to making this change, but would like to vet the idea a bit.

**Comment by jbrinkman** [comment]
Part of the reason for this suggestion and others is to minimize the work needed every time I create a new site.  This currently requires too many clicks for what could be simple defaults.

**Comment by nvisionative** [comment]
Understood @jbrinkman - let's hear from others on this.  Making this change is a simple one technically speaking, but it would go against what others have said they want.  I will say that we only polled a few people though, so we could have gotten it totally wrong!  LOL!  :)

**Comment by hismightiness** [comment]
With this being already out there and live, it would have been nice to already have thought of this before launch.  Perhaps there can be a configuration file somewhere to change how this works?  That said, I love this idea.

**Comment by nvisionative** [comment]
The idea of an app setting sounds like a reasonable one.  We are going to need a settings area in the app anyway for implementing some other planned updates, so we should probably just go with this approach.

**Comment by jbrinkman** [comment]
Here is a short video showing all of the extra work I think is currently required when creating a site: http://screencast.com/t/8jfbAdbYE

**Comment by hismightiness** [comment]
Great video and lots of great feedback in that video, @jbrinkman.  Thank you for taking the time to put that together and participate with this project.  I know everyone in the community appreciates it.  However, like a DNN Jira item, I think each enhancement you suggest deserves its own issue here.

**Comment by nvisionative** [comment]
@jbrinkman thanks so much for the video - that is extremely helpful!  Would you mind creating a separate issue for each issue you would like to see addressed?  You can simply attach the same video to each issue just to make it easier for you.  Thanks!
