### ISSUE TITLE
Auto-create website folder if it doesn't exist

### ISSUE THREAD

**Issue by jbrinkman** [nvisionative/nvQuickSite#108]
When creating a new site, if I type in a location that doesn't already exist, the system should prompt me to automatically create the directory rather than just displaying an "error" message.  If I mistyped the directory name, this would give me the opportunity to correct my mistake.

**Comment by nvisionative** [comment]
@jbrinkman - great feedback!  We did not account for this scenario.  We'll mark this for inclusion in the next version.  Thank you!

**Comment by hismightiness** [comment]
I agree.  This is a great idea!  Especially if it does indeed prompt before creating the folder.  An add-on to this might be including a checkbox with the prompt to say "Don't warn me again".

**Comment by nvisionative** [comment]
Great ideas @jbrinkman and @hismightiness.  We'll see if  we can get this rolled into the next release.

**Comment by nvisionative** [comment]
@jbrinkman & @hismightiness - I am literally chuckling out loud right now!!!  I just finished coding the proposed solution and went to test it out.  In testing I discovered we had already accounted for this by not allowing the user to type in the Location.  This field already forced the user to utilize the folder browser dialog to  select a Location.  So...given this new enlightenment, do you think the Location field should just be a plain textbox that DOES allow the user to type in their desired directory?  We pretty much have the proposed solution created.  It involved creating a custom dialog form (which can be reused in other areas if needed) that includes the checkbox to "Do not warn me again".  It just needs to be tested and we can commit the code.  If I don't hear from you shortly today, I'll probably go ahead and implement this as a new feature and we can rollback if desired.
