### ISSUE TITLE
Allow me to use any local package

### ISSUE THREAD

**Issue by jbrinkman** [nvisionative/nvQuickSite#109]
If I try to use a local package (e.g. nightly build, beta, evoq package, custom distro etc.), then nvQuickSite complains that I haven't picked a valid package.  I should be able to use any valid DNN package that I want without being limited to just what appears in the dropdown list. The dropdown list should just be a shortcut list for "known" packages, but the system shouldn't prevent me from using a package of my own.

**Comment by hismightiness** [comment]
Hello Joe:

Thank you for creating an issue for this.  Could you please attach an example package to this issue that isn't working for you?

**Comment by jbrinkman** [comment]
I can't because it is an Evoq installation.  I'll see if I can repro with a nightly DNN build.

**Comment by nvisionative** [comment]
@jbrinkman can you point to an example nightly build file that doesn't work?  We will be happy to test it out.  Thanks.

**Comment by bhattjidotcom** [comment]
Hey Joe,

You mean you downloaded the nightly build on local machine, pointed the "location" to the downloaded file, and then it didn't work?

**Comment by jbrinkman** [comment]
So the issue turns out to be that nvQuickSite is hardcoded to look for certain package names.  See this demo video http://www.screencast.com/t/jboH6v13 Given that we want to enable custom distributions at some point, and that all Evoq packages are in fact just DNN installs with some extra modules, it would seem that relying on packages names as a verification is not an optimal validation check.  Instead I would suggest looking for well known directories inside the package like desktopmodules and portals.

**Comment by nvisionative** [comment]
Thanks.  Validation for install packages are a bit more complex.  Currently there is no built-in support for Evoq install packages, but we are open to dialog about this.

**Comment by jbrinkman** [comment]
I have looked at the code but it appears that all of the package validation logic is isolated in a separate assembly. Is that assembly Open Source?  If so is the source code somewhere we can inspect it?

**Comment by nvisionative** [comment]
@jbrinkman we will go ahead and accept this request and get it in the queue for a future release.  That release will allow installation of any DNN install package (Platform, Evoq or custom).  Thanks!
