### ISSUE TITLE
Question prompt looks/sounds like an error

### ISSUE THREAD

**Issue by hismightiness** [nvisionative/nvQuickSite#116]
Windows 8.1
nvQuickSite 1.1.0

When you select a local package, the app prompts you to confirm which package you intended to use, like shown below.

![nvquicksite-prompt-issue-01](https://cloud.githubusercontent.com/assets/938023/17001051/320fd556-4e7a-11e6-90fd-7da7cde3bb2b.png)

The UI makes this look like an error.  

Suggested changes:
- Change "Use Local Install Package" to "Confirm: Use Local Package?"
- Remove or replace the warning icon
- Change "Local Install Package already defined. Use it?" to "Click 'Yes' to use the local installation package. Clicking 'No' will download the selected package instead."

**Comment by nvisionative** [comment]
Thanks for the great feedback @hismightiness!  We were not 100% happy with the existing implementation, but felt like someone would offer a better approach once it is out in the wild.  We are thinking the following still has room for improvement:

"Click 'Yes' to use the local installation package. Clicking 'No' will download the selected package instead." 

Perhaps it should be:

"Click 'Yes' to use the Local Install Package. Click 'No' to attempt download of the selected Download Install Package."

Thoughts?

**Comment by hismightiness** [comment]
@nvisionative Sounds good to me.

**Comment by nvisionative** [comment]
Okay @hismightiness - we'll put this enhancement in queue for the next release.

**Comment by nvisionative** [comment]
@hismightiness how is this?  If agreeable, we'll go ahead and commit the change.  Thanks again for the feedback!

![screencapture_71 jul 22 22 28](https://cloud.githubusercontent.com/assets/4568451/17075239/b583b62c-505b-11e6-9d46-6dd26b621f4a.png)

**Comment by hismightiness** [comment]
That's definitely better than the last dialog.  I'm okay with it.

**Comment by nvisionative** [comment]
Thanks, we can work on the cosmetics via another issue.  Did you want to create that issue?

**Comment by nvisionative** [comment]
This was resolved via commit for issue #118
