### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by leigh-pointer** [nvisionative/nvQuickSite#120]
On the website you might want to add Microsoft SQL Server 2016 to supported databases

**Comment by hismightiness** [comment]
@leigh-pointer  Thank you for the issue.  I'm fairly certain that SQL Server 2016 can be and is supported, but what you see listed is what's been tested against.  I don't think SQL 2016 was tested by anyone in this project.

**Comment by nvisionative** [comment]
@leigh-pointer - @hismightiness is correct, we have not tested this against MSSQL Server 2016.  However, we foresee no issues with it.  We can add it to the list as soon as it is tested.  If you test it and have good results, please report back and we'll make the change.

**Comment by leigh-pointer** [comment]
I have tested against MSSQL 2016 and have no issues to report.  Everything ran/installed/processed as expected.

**Comment by nvisionative** [comment]
Wonderful @leigh-pointer - thanks for testing this out and reporting back.  We'll update the docs.
