### ISSUE TITLE
Update HOSTS File

### ISSUE THREAD

**Issue by Sean6971** [nvisionative/nvQuickSite#121]
I get this error after putting information in for the Database. What can i do to get passed this? (probably an easy fix!)

![error](https://cloud.githubusercontent.com/assets/20888302/17462897/764bf934-5c80-11e6-8aaf-eb783e13e903.jpg)

Thanks for any help!

**Comment by hismightiness** [comment]
Have you tried running the app "As Administrator"?

**Comment by Sean6971** [comment]
Yes, Sir!

**Comment by hismightiness** [comment]
Interesting... I just checked mine and I'm not even running as admin.  

What version of Windows are you on, and do you have your Windows Updates all applied?

**Comment by Sean6971** [comment]
I am using Windows 7 Home Premium and I just checked, and no updates needed. I have tried running in  "As Administrator" and tried running it not as administrator. I have tried downloading different install packages from Platform 8.0.3 to 7.4.0 (not every version!) and get the same error every time. :-(

**Comment by hismightiness** [comment]
Just to be sure, you are running the latest version, 1.1.0, right? 

https://github.com/nvisionative/nvQuickSite/releases/tag/v1.1.0

**Comment by Sean6971** [comment]
Yes I am! :-)

**Comment by hismightiness** [comment]
@nvisionative I'm out of questions here, and I'm unable to duplicate the issue.  Can you look into this one?

**Comment by hismightiness** [comment]
@Sean6971  Actually... I do have one more question.  You don't have the HOSTS file open when you run the program, do you?  Generally, this kind of error occurs either due to (1) invalid permissions, or (2) file locked or in use.

**Comment by nvisionative** [comment]
nvQuickSite actually forces running as an Adminstrator.  So this is most likely a permissions issue within the local environment or perhaps the file is in use (open) by another process/app.

**Comment by nvisionative** [comment]
Unable to replicate - closing issue.
