### ISSUE TITLE
Creation website fails

### ISSUE THREAD

**Issue by Tychodewaard** [nvisionative/nvQuickSite#123]
Installing NVquicksite went well.
Creating a new website not so much.
Final tab: Database info I have:

- database server name: (local)
- database name DNN804
- Windows authentication
- When I press next, I get an error. 
"Can't find Microsoft.Web.Administration" (screen capture)

I'm running IIS 8, .NET 4.6 on a Surface Pro 3

The file does exist btw. It's located in C:\Windows\WinSxS\amd64_microsoft.web.administration-nonmsil_31bf3856ad364e35_10.0.14393.0_none_f5e53e9ca789ab77

Any suggestions on this?
Kind regards
Tycho

![image](https://cloud.githubusercontent.com/assets/9091997/19151797/08f56dba-8bcf-11e6-85b0-d04f7fa94a36.png)

**Comment by hismightiness** [comment]
Hey Tycho:

I'm pretty sure this environment hasn't been tested against, so thank you for reporting the error.  Do you have additional information in the "Details" section?  Preferably, translated to English?

**Comment by nvisionative** [comment]
@Tychodewaard it appears you may not have Web Management Tools enabled in IIS.  Please open your Windows Features and enable Web Management Tools.  See screenshot:

![screencapture_ 2016-10-06 12 06 pm _740](https://cloud.githubusercontent.com/assets/4568451/19160363/947af06a-8bbd-11e6-9319-d9670aceb153.png)

Let us know if this works or not.

**Comment by Tychodewaard** [comment]
Thanks @hismightiness and @nvisionative !
I changed the settings in Turn Windows features on/off.
After that NVquicksite has a different error.
The first error (screen cap 40) says (excuus me for horrible text but translation from Dutch does that) "Can not establish a trusted relation between this workstation and the primary domain"

The Second error (Screencap 41) says "There is a network error or specific error while connecting with SQL server. Server has not been found or accessible. Check the name and whether SQL Server allows external connections".

The last screen cap (43) is from my settings. Maybe I need to check the fourth (Scripts and tools for IIS management) as well? 

Tycho
<img width="343" alt="schermopname 43" src="https://cloud.githubusercontent.com/assets/9091997/19165058/9d76c294-8c02-11e6-8d38-98088863d358.png">



<img width="479" alt="schermopname 40" src="https://cloud.githubusercontent.com/assets/9091997/19164829/d1fa83da-8c01-11e6-97af-72be8295ddf7.png">
<img width="480" alt="schermopname 41" src="https://cloud.githubusercontent.com/assets/9091997/19164830/d1fd0790-8c01-11e6-910c-56b0cf1b6342.png">

**Comment by nvisionative** [comment]
@Tychodewaard the first error can just be ignored for now.  This is a known issue that happens for some people ( see #110 ) and it most like has to do with the version of SQL Server you have installed.  What version of SQL Server do you have installed?

The second error sounds like a connectivity issue with SQL Server.  Perhaps you do not have Named Pipes enabled?  This can be enabled in the SQL Server Configuration Manager.  When accessing your local database via SQL Server Management Studio, do you login using "(local)" as the database name or a named instance?

You should not need to enable Scripts and Tools for IIS.

**Comment by hismightiness** [comment]
@nvisionative FYI - I never keep shared pipes enabled and it works beautifully for me.  I only have TCP/IP enabled for all editions of SQL that I keep installed.  (Unless a Windows update has changed something at some point and I haven't noticed.)

**Comment by nvisionative** [comment]
@hismightiness Using "(local)" is for a non-named server instance and I thought you had to have Named Pipes enabled to use that.  Perhaps I am wrong.

@Tychodewaard can you confirm whether or not your SQL Server instanced is a named instance or a non-named instance?

**Comment by Tychodewaard** [comment]
@nvisionative SQL Server is a non named instance. I just changed the Named pipes to enabled, restarted SQL server and...the same error...

**Comment by nvisionative** [comment]
@Tychodewaard when you log into SQL Server via SQL Server Management Studio, are you using "(local)" for the database name there?  And do you have more than one SQL Server instance running on your computer?

**Comment by Tychodewaard** [comment]
It took some time but it's working now. Not all settings in IIS were set correctly...
Just installed the nightly build and I'm off getting my hands dirty with DNN9 :-)

Thanks for the response!
Tycho

**Comment by nvisionative** [comment]
Glad you got it working @Tychowaard!  If you don't mind, please share what IIS settings you had to change.  It may help others.  Also, it is nice to know it is working with the DNN9 nightly builds! ;-)

**Comment by Tychodewaard** [comment]
To be sure I reinstalled SQL and IIS. And I turned on World wide web services including subsettings... #feelingabitsheepish
