### ISSUE TITLE
Override default settings

### ISSUE THREAD

**Issue by jbrinkman** [nvisionative/nvQuickSite#124]
Often when creating new DNN sites for demo or test, there are a few settings that I would like to "tweak".  This currently requires me to do the install, and then manually go into web.config and the host or site settings and make a few changes.

It would be nice if I could go into an advanced section of the installer and make those setting changes directly so that they are automatically configured as part of the DNN installation. I would like to be able to add settings individually or to be able to load a standard settings file that includes my standard overrides (PersistentCookieTimeout, SMTP settings, host user password, etc.).  I should be able to override settings in web.config or from the DotNetNuke.Install.Config.Resources file.

**Comment by nvisionative** [comment]
Thanks @jbrinkman - let's plan on collaborating at the DNN Summit Code-A-Thon.

**Comment by david-poindexter** [comment]
Closing due to no community traction.  With the release of v2.0.0, contributions should be much easier due to massive refactoring and improvements in the code base.
