### ISSUE TITLE
Add ability to upgrade site

### ISSUE THREAD

**Issue by jbrinkman** [nvisionative/nvQuickSite#125]
Often when doing demos or testing, I need to handle both installation as well as upgrade scenarios.  It would be nice to have the ability to choose to do a new install or an upgrade of an existing site. If an upgrade is requested, then the user would need to identify the URL and file location for the website along with the version that they want to upgrade to.  Once that information is provided the upgrade package would be extracted over the top of the website and upgrade process initiated.

**Comment by nvisionative** [comment]
Thanks @jbrinkman - let's plan on collaborating at the DNN Summit Code-A-Thon.  This one is certainly not trivial.  :-)

**Comment by abukres** [comment]
It's preferable this functionality can also backup and restore the database and the installation in case the upgrade messes up the DNN site.

**Comment by david-poindexter** [comment]
Closing due to no community traction.  With the release of v2.0.0, contributions should be much easier due to massive refactoring and improvements in the codebase.
