### ISSUE TITLE
Eliminate Install Wizard

### ISSUE THREAD

**Issue by jbrinkman** [nvisionative/nvQuickSite#126]
nvQuicksite currently only performs part of the installation process.  Once nvQuickSite is complete, the user must still complete the DNN Install Wizard. It would be good to allow the user to provide the host username and password and then perform an automated install so that the entire installation process is completed by nvQuickSite.

**Comment by nvisionative** [comment]
Thanks @jbrinkman - let's plan on collaborating at the DNN Summit Code-A-Thon.  This one sounds like a great one to tackle!

**Comment by nvisionative** [comment]
@jbrinkman we are going to close this issue as it seems to be getting more traction via #132
