### ISSUE TITLE
Seperate project into a UI and a Command line part

### ISSUE THREAD

**Issue by donker** [nvisionative/nvQuickSite#127]
This would make it a solution with two projects. The idea is to make a part that can be used with Powershell for instance so you can script installs. That would make the product more attractive for power users.

**Comment by bizcomit** [comment]
I totally agree with @donker ! 
a very useful feature would be to be able to create portals or sub-portals in existing installations, starting from XML / Json template files and being able to fetch these templates from external URLs, so as to make them dynamic the creation of templates.

**Comment by david-poindexter** [comment]
Closing due to no community traction.  With the release of v2.0.0, contributions should be much easier due to massive refactoring and improvements in the codebase.
