### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jncraig** [nvisionative/nvQuickSite#130]
Here's the problem:

<img width="576" alt="error" src="https://cloud.githubusercontent.com/assets/4732485/23134190/df8154c2-f761-11e6-81e0-0ec7caff162b.png">

**Comment by jncraig** [comment]
Oh!  What is means is ... IIS isn't enabled ...

Doh!

**Comment by nvisionative** [comment]
@jncraig you will need to install the IIS Management Console via Windows Features.  See following screenshot. 

![screencapture_ 2017-02-20 12 42 pm _978](https://cloud.githubusercontent.com/assets/4568451/23136301/1ca55b16-f76a-11e6-8a66-868a047f8e55.png)

**Comment by jncraig** [comment]
Yup!
