### ISSUE TITLE
Display nvQuickSite version on UI

### ISSUE THREAD

**Issue by bradbamford** [nvisionative/nvQuickSite#131]
Open the app and there's no way to know what version of nvQuickSite is running, and secondly how does the user know if it is the latest version?

**Comment by nvisionative** [comment]
Great enhancement request!  

For now, you can view **File > Properties > Details** for **nvQuickSite.exe** (which by default will be located in **C:\Program Files\nvisionative\nvQuickSite** or **C:\Program Files (x86)\nvisionative\nvQuickSite**.  It will look like the following:

![screencapture_ 2017-09-27 08 33 pm _1198](https://user-images.githubusercontent.com/4568451/30944012-1f49b53c-a3c3-11e7-9462-1934662a8c66.png)

**Comment by abukres** [comment]
In PR #146

**Comment by nvisionative** [comment]
Resolved via PR #146 - thank you @abukres for your contribution!
