### ISSUE TITLE
Add an option to install with default options

### ISSUE THREAD

**Issue by richard-edwards** [nvisionative/nvQuickSite#132]
Would be great to have an option where instead of going to the standard DNN install screen where you put in the host username, password, template etc., it just does the default install by going to the base url of the site + /install/install.aspx?mode=install

For instance, instead of going to http://dnn720.dnndev.me, it would go to http://dnn720.dnndev.me/install/install.aspx?mode=install

**Comment by nvisionative** [comment]
Great idea @redwards1966 - this would indeed be a great feature.

**Comment by redwards1966** [comment]
I forked the project earlier but had some issues compiling. Looks like the packages got restored but VS2017 was still complaining about a few references such as Metro Framework and Newtonsoft JSON for some reason. What version of VS are you successfully compiling in. I was going to implement this feature request and create a PR

**Comment by nvisionative** [comment]
@redwards1966 thank you for your interest in doing a PR.  That would be awesome!  

Sounds like you may be dealing with NuGet issues.  Sometimes doing a "Clean" and then "Rebuild" will fix this.

We are using VS2015 here for this project.

**Comment by david-poindexter** [comment]
Closing due to no community traction.  With the release of v2.0.0, contributions should be much easier due to massive refactoring and improvements in the codebase.
