### ISSUE TITLE
Provide custom/optimized distributions of DNN

### ISSUE THREAD

**Issue by iJungleboy** [nvisionative/nvQuickSite#133]
Since this is an awesome easy way to install DNN, it would also be great if it could be used to (quickly) and automatically install distributions, like

1. a Hotcakes distribution
2. a content management distribution (with 2sxc)
3. a NBStore distribution
3. a DNN Sharp Dist
3. a Mandeeps Dist
3. an xmod-dist
3. etc.

Basically I would envision something, which would look a bit like this:

![image](https://user-images.githubusercontent.com/5321186/32042060-aa48cd10-ba36-11e7-99f7-06ff34cd50cd.png)

## Example with 2sxc CMS Single-Page with DNN 9.11
This could then look like this:
![image](https://user-images.githubusercontent.com/5321186/32042081-ba1d5210-ba36-11e7-8d54-8ad4d1b3c92e.png)

## one or two dropdowns
I could imagine that the first dropdown would contain all DNNs - OR it would simply contain the distribution name like 
* Basic DNN Platform
* eCommerce with Hotcakes
* eCommerce with NBStore
* Content Management with 2sxc
* Solution Development with DNN Sharp
* Social Site with Mandeeps

In the second dropdown, the user would then see the versions which are available. 

I'm certain this is technically not difficult to implement, but the core challenge would be ensuring that these distributions are added regularly (for example, 2sxc releases a new 9.x version ca. every month) without overwhelming @nvisionative, and ensuring that there are no cr** distributions. But I think this would be amazing. Any chance of supporting this?

**Comment by nvisionative** [comment]
@iJungleboy thank you so much for the suggestion.  Issue #128 will address the location of "the core DNN list" being on GitHub.  Therefore, we can imagine a slight change to this UI/UX to support "other distributions".  We'll see if we can work on that a bit and propose it back here for review/feedback.  In the meantime, you can install other distributions via the **Local Install Package** option.

**Comment by iJungleboy** [comment]
Thanks. I have an additional suggestion: the primary xml which listst which distributions exist, should come from nvisionate, and just contain a link to other XMLs like that of 2sxc / hotcakes, so that these suppliers can do their own release management. This way you can withdraw them from the list if the quality turns out to be bad, but you are not forced to manage each release.

**Comment by nvisionative** [comment]
Question for others viewing this...how many of you have **special distributions** of DNN?  Would this feature benefit the greater community or just a select few?

**Comment by hismightiness** [comment]
@nvisionative This is a great question.  My primary concerns with any update to nvQuickSite are (1) does it benefit the community overall, and (2) does it impact the usability of nvQuickSite in any way?

**Comment by iJungleboy** [comment]
So for 2sxc - we don't have a special distribution ATM, simply because we haven't found additional value, as we would end up writing even more tutorials etc. just to install that as well. But we would create one right away, if this were supported.

**Comment by Tychodewaard** [comment]
There are several reasons I would be very interested:

1. Saves time for setups
2. Great inspiration for 'solutions', especially if it is shipped including content. 
In future you even might offer paid distributions and keep 15% to yourself. NVQuicksStore :-)
3. It is a pointer that modules within a distribution can play nicely together
4. It is a pointer that modules work within a specific setup like multi language.

Besides possible issues Daniel mentioned, I have some more issues/questions/features/comments
- Maintenance of links to other suppliers. This might be automated and if I understand correctly, it would not need an upgrade of NVQuicksite
- Distributions can have commercial modules. 
* it should be marked as such
* it should mention the version number and release date of the module in the distribution. That way you know whether you need to renew a license or not
- In an ideal world it's clear whether a module is working in another DNN version and/or in the same instance with other modules. As we are not in this perfect world, it should be clear (UX/design) that people have their own responsibility to check that. 
- How can I add my own distribution? Export a site might be one way. But for multi-portal solutions (like multi stores) you need a full back up. And than wetransfer that to @nvisionative or @hismightiness ?

Hope this gives some feedback.

Cheers
Tycho

**Comment by iJungleboy** [comment]
To all: Just updated the intro a bit, with better screenshots & examples. 

@Tychodewaard 
1. yes, idea is that the distribution-suppliers are in charge of their releases
2. I believe they could and should have commercial modules - assuming these have a licensing that can be activated
3. Versions - yes, these (more than 1 version, 2sxc 9.7 + dnn 9.11, ... should be texted by the supplier)
4. The installation should adhere to dnn installation processes, so should not include DB images. This is a bit more complex to deliver (as a supplier), but ensures it works in various hosting environments, where mounting an image is often not an option.

**Comment by donker** [comment]
Last year I chatted with David about something similar called "**recipes**". We could envision recipes as scripts that tell the installer what to get and where to get it from. Then we, as a community, could maintain a public repo of recipes that would allow us to maintain these. The user could add their own private recipes.

This approach would solve a world of issues. Namely:

1. You don't have to host entire packages any longer that may or may not infringe upon the rights of others (at the time it was still unclear whether DNN would be favorable to anyone else hosting a package including the base platform).

2. By not hosting 3rd party software yourself you also absolve yourself of liabilities. What if you accidentally are distributing something that is wrong?

3. Recipes could extend to include more things than just extensions. Imagine leveraging the DNN Prompt work for this as well.

4. Hosting and maintaining recipes is far less work. Prompting others to submit more IMHO.

Peter

**Comment by iJungleboy** [comment]
@donker I really like it. It's more development on the DNN installer and/or nvQuickSite, but would then make adding (or customizing another) specialized distribution a breeze!

**Comment by meetmandeep** [comment]
We also intend to offer our own distributions in future.

**Comment by donker** [comment]
@iJungleboy I think that indeed it requires work at both sides. This is why I brought Kelly (DNN Prompt) in touch with @nvisionative about this to try to get this vision in a longer term future for these products. I think both the quicksite installer and DNN Prompt solve essential bits for our ecosystem right now and could provide a valuable impuls in the future. Kudos to the visionary individuals involved.

**Comment by iJungleboy** [comment]
It's important to remember that many of these recipe parts must run during installation; for example before the portal is created. Otherwise a distribution couldn't include a site-template.

**Comment by iJungleboy** [comment]
I created a separate issue to discuss Peters recipes - since it may be an alternative or addition to this idea - #134. At the moment I think it would probably be an even better idea than this, but I think that discussing both would be very valuable.

**Comment by nvisionative** [comment]
Great conversation everyone!  Thank you for participating.  It seems we may have two separate ideas here for sure.  This one could possibly be a stepping stone to the "Recipes" solutions, but I would want to flesh out the UI/UX a bit to make sure we don't shoot ourselves in the foot here.  :)
