### ISSUE TITLE
Enable installations using Recipes (kind of like custom installations/distributions)

### ISSUE THREAD

**Issue by iJungleboy** [nvisionative/nvQuickSite#134]
This is an alternative installation enhancement suggestion to #133 (enable custom distributions) which is basically an idea @donker brought up. I would like to create a separate thread, to keep the thoughts / ideas separated from each other. 

I will quote @donker on this: 
> Last year I chatted with David about something similar called "recipes". We could envision recipes as scripts that tell the installer what to get and where to get it from. Then we, as a community, could maintain a public repo of recipes that would allow us to maintain these. The user could add their own private recipes.
> 
> This approach would solve a world of issues. Namely:
> 
> You don't have to host entire packages any longer that may or may not infringe upon the rights of others (at the time it was still unclear whether DNN would be favorable to anyone else hosting a package including the base platform).
> 
> By not hosting 3rd party software yourself you also absolve yourself of liabilities. What if you accidentally are distributing something that is wrong?
> 
> Recipes could extend to include more things than just extensions. Imagine leveraging the DNN Prompt work for this as well.
> 
> Hosting and maintaining recipes is far less work. Prompting others to submit more IMHO.
> 
> Peter

I believe the solution would look a bit like this - and I hope for improvents / changes from you all:

1. Basically it needs a file (xml or json) which contains the installation recipe
1. the recipe would need to contain various instructions, incl.
    1. (maybe) additional parameters needed for the installation to work - this could be a choice or something
    1. DNN Platform specs (what installation to start with)
    1. (maybe) things to do before dnn install starts, like copying additional modules?
    1. Packages to auto-install right after the basic installation (kind of like putting them in the install-folder)
    1. Settings which affect the initial 1 (or many) portals installations, like templates to use
    1. post install actions
    1. clean up (like removing the packages from install
1. these recipes could then be used manually (in nvQuickSite :) or another installer...
1. ...or would be managed in a repository - in which case the xml/json would need extra metadata like author, description, version, etc.

So this is just my 2cents - any corrections to the basic idea you would like to note - or feel free to link to further docs if these already exist.

**Comment by david-poindexter** [comment]
Closing due to no community traction.  With the release of v2.0.0, contributions should be much easier due to massive refactoring and improvements in the codebase.
