### ISSUE TITLE
nvQuickError When Trying to Install Local Evoq Engage Package

### ISSUE THREAD

**Issue by CBPSC** [nvisionative/nvQuickSite#135]
I downloaded an Evoq Engage 9.1.1 package locally and tried to use nvQuickSite to install it. It presents me with an error message related to a local install package & will not let me proceed past the initial screen. 

See the attached screen shots for where I get stopped.

![nvquickerror-1](https://user-images.githubusercontent.com/4571863/34304210-b7f63608-e706-11e7-9733-69b3cd6ddf2f.jpg)
![nvquickerror-2](https://user-images.githubusercontent.com/4571863/34304211-b7ffeafe-e706-11e7-94a2-86fc288c4fed.jpg)

**Comment by nvisionative** [comment]
@CBPSC thank you for reporting this.  We have been able to replicate this behavior locally.  This will be address in the next release.

**Comment by nvisionative** [comment]
@CBPSC this was actually resolved by the same commit that resolved #109.  This will be in the upcoming release.  Thanks again for reporting this!
