### ISSUE TITLE
Ensure IIS & Necessary Features Installed Before Installing DNN

### ISSUE THREAD

**Issue by CBPSC** [nvisionative/nvQuickSite#138]
As discussed in [the comments on this blog](http://www.dnnsoftware.com/community-blog/cid/155489/iis-gotchas-when-installing-dnn#Comments) I believe nvQuickSite should check to see if IIS is installed and the necessary IIS features required to run a DNN site are installed before proceeding through the install wizard. 

This could be done quietly in the background or with a simple prompt "_IIS is not installed and is required to run DNN, would you like nvQuickSite to install & configure this for you? - YES | NO_"

or the prompt could also say something like 

"_IIS is installed, but the necessary features of IIS to run DNN are not enabled, would you like nvQuickSite to enable the required features? YES | NO_"

Ensuring these features are installed will only help ensure all users of nvQuickSite have a positive experience installing DNN.

**Comment by nvisionative** [comment]
@CBPSC we are doing some clean up of issues and will be closing this one.  However, we are going to link it to #150 see we don't lose the ideas remitted here.  Please feel free to re-open if necessary.
