### ISSUE TITLE
"Unrecognized attribute 'targetFramework'" error when visiting site

### ISSUE THREAD

**Issue by abukres** [nvisionative/nvQuickSite#140]
"Unrecognized attribute 'targetFramework'" error in web.config error when visiting site.
That's because the app created a v2.0 .Net framework version of an IIS App pool instead of v4.0.
Windows 7.

**Comment by nvisionative** [comment]
Okay, I am not sure hard-coding to v4.0 is ideal, as some users will not have that.  I agree there is something that needs to be done about this, but perhaps there are some additional checks that can be done to determine what is available and what is is used as a result.  We should be developing for the lowest common denominator given the relevant/current/utilized technology stack.  Any more thoughts on this?

**Comment by abukres** [comment]
The lowest common denominator is v2 and that's too low for DNN requirement and it's the reason for this fix. nvQuickSite targets .NET 4.5 which means the app wouldn't even run if v4 doesn't exist on the same machine.

**Comment by nvisionative** [comment]
LOL - you make a VERY valid point.  The piece of the puzzle that is in my head (and thus unknown to you) is that I had planned to work on supporting older versions of DNN at some point (just for the fun of it).  That said, this should be a good patch for the current issue a d we can work on supporting older vers of DNN in the future (if ever).  Thanks again for your contributions!
