### ISSUE TITLE
"Some or all identity references could not be translated" error

### ISSUE THREAD

**Issue by abukres** [nvisionative/nvQuickSite#142]
This error seems to occur when you're not using the default SQL Server instance but a named instance. The app is using a hard coded 'NT Service\MSSQLSERVER' which is for the default instance and if this instance doesn't exist, the login won't exist and the error appears. The named instance name is used in the SQL Server login name therefore the app needs to figure out the NT Service\xxxxx name dynamically and use it for the dbServiceAccount variable.  This issue will also affect SQLExpress as 'sqlexpress' will be in the login name too.

**Comment by nvisionative** [comment]
Good call @abukres!

**Comment by nvisionative** [comment]
Resolved via PR #145 - thank you @abukres - this was one of the most annoying errors to date and you figured out the resolution!  🥇
