### ISSUE TITLE
UI should reflect the current version of the app

### ISSUE THREAD

**Issue by hismightiness** [nvisionative/nvQuickSite#143]
The UI needs to show what version the app is.

Another feature that would be nice is to visually indicate whether the app has a newer version available.  It could point to:

https://github.com/nvisionative/nvQuickSite/releases/latest

**Comment by nvisionative** [comment]
Excellent feedback @hismightiness - we will try to work this into the next release.

**Comment by abukres** [comment]
Is there a specific webapi to call to get the release number or did you mean scrape the page? I think it can simply be in the PackageManifest.xml file of nvQuickSite.

**Comment by nvisionative** [comment]
@abukres I believe @hismightiness is referring to the version of nvQuickSite, not DNN.  Since version is a part of the assembly info, we would just need to surface this version number somewhere in the UI.  We will handle this one.

**Comment by nvisionative** [comment]
Hey @abukres you are on a roll!  I just saw a PR for this and will review as soon as possible.  Moving forward, can you please check out [THIS METHOD](https://help.github.com/articles/closing-issues-using-keywords/) for referencing issues within your pull requests.  This will save considerable manual work on our end.  Thanks again for all the help on this project!

**Comment by nvisionative** [comment]
@hismightiness let's split this issue into two separate issues.  The first issue has already been resolved, thanks to @abukres, and will be included in the upcoming release.  Can you create another issue for **showing upgrade availability**?

**Comment by nvisionative** [comment]
@hismightiness we are actually doing considerable clean-up on this repo today, so we'll go ahead and create the new issue for you just to save a bit of time and allow us to close this issue.  Thanks again for suggesting these enhancements!
