### ISSUE TITLE
Error message if iis pool already exists

### ISSUE THREAD

**Issue by abukres** [nvisionative/nvQuickSite#147]
An error message shows up if IIS pool already exists. App should ask user if they want to use it or recreate it.

![nv](https://user-images.githubusercontent.com/6255956/35201150-bfe9c954-fecd-11e7-9362-1ca6cd8a7e43.gif)

**Comment by nvisionative** [comment]
@abukres we have not been able to reproduce this error.  Can you provide the exact steps you are taking to result in this error?  Thanks!

**Comment by abukres** [comment]
Can't reproduce so I am closing this.

**Comment by nvisionative** [comment]
Thanks for the follow-up @abukres - if you run into this error again, please do let us know the steps.  There is code already in place that is supposed to take this scenario into account and handle appropriately.  So we are really curious as to how this occurred.  :)  Perhaps there is some flawed logic somewhere.
