### ISSUE TITLE
Path get's mangled if there is a slash too much

### ISSUE THREAD

**Issue by iJungleboy** [nvisionative/nvQuickSite#148]
If the root path contains a slash - so `c:\projects\` instead of `C:\projects` the final path in IIS is incorrect, resulting in an install that shows this error:

C:\Projects\\test-dnn911\Website\web.config

![image](https://user-images.githubusercontent.com/5321186/35504675-f539ca20-04e3-11e8-868f-a41c25b54643.png)

**Comment by nvisionative** [comment]
Good catch @iJungleboy - we should check for trailing `\` and trim accordingly.
