### ISSUE TITLE
Update Block Button Links

### ISSUE THREAD

**Issue by CBPSC** [nvisionative/nvQuickSite#156]
Suggesting to make some updates to the banners that are displayed when using nvQuickSite.

Suggestions:

- Find somewhere to add in "Follow DNN Awareness"
- Replace "DNN DevSpark" with a link to "nvQuick.com"

Also, it may be helpful to change these every so often so that the users who often use the solution won't train their eyes to not look at this section of the tool. If possible, maybe change the back-end code so that - at your convenience - you could change out the banners with timely info such as promoting conferences, user group meetings, and special projects which may need OSS attention

**Comment by nvisionative** [comment]
Thank you @CBPSC for the enhancement request - we will see what we can do!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nvisionative** [comment]
@CBPSC we will be submitting a pull request for the below shortly.  Thank you again for your recommendations.  It is DNN community members like you that make it a pleasure to serve and make DNN a great experience!

![screencapture_ 2018-03-04 12 47 pm _1500](https://user-images.githubusercontent.com/4568451/36948540-51ac7826-1faa-11e8-88f7-1921119dc3e0.png)
