### ISSUE TITLE
Is is possible to install a customised DNN site?

### ISSUE THREAD

**Issue by StephenBugden** [nvisionative/nvQuickSite#165]
Hello,

Could I please ask if it's possible for me to package up a DNN site that I've built for installation via nvQuicksite? I mean I would like to take a clean install, then add some modules, change the configuration, create some pages, add some content etc. then take that and package it up into a zip file that could be installed using nvQuickSite.

If it is possible, is there any documentation that explains how to create the contents for the zip file?

Best Regards,

Steve

**Comment by nvisionative** [comment]
@StephenBugden again, this is beyond the scope of the nvQuickSite project.  I would recommend you post this question in one of the many DNN forums or Q&As.  The short answer is...it is possible, and as long as you follow best practices, nvQuickSite will install it just fine.  For instance, Evoq is really an production example of what you are talking about.  Is is a custom "distribution" of DNN, but packaged in the same manner as the core DNN Platform.

**Comment by StephenBugden** [comment]
Hello,

Thank you for your reply, again I'm sorry for posting in the wrong place in that case. I was assuming the zip needed specific packaging for nvQuickSite.

Steve

**Comment by nvisionative** [comment]
No worries @StephenBugden - nvQuickSite will install any DNN install package that follows best practices in its creation.
