### ISSUE TITLE
Check Environmental Minimum Requirements Prior to Installing

### ISSUE THREAD

**Issue by hismightiness** [nvisionative/nvQuickSite#166]
It would be great for there to be a check for the minimum requirements after selecting the installation package to be used.  The package name could be used and mapped to a listing of requirements for the SQL Server, IIS, .NET, etc.

When a requirement is found to be missing or incompatible, a message should be shown.  In the event that more than one requirement is found to be deficient, all should be listed.  In the future, this could be further enhanced to give more directions on how to meet the requirements.

**Comment by nvisionative** [comment]
@hismightiness thanks for the post.  We have plans to address much of this upon installation of nvQuickSite - see #150 .  However, we realize you are speaking of something slightly different, so we'll let this issue open.

**Comment by nvisionative** [comment]
@abukres the minimum requirements are listed [HERE](https://github.com/nvisionative/nvQuickSite/wiki/Minimum-System-Requirements) and [HERE](https://www.nvquicksite.com).

**Comment by abukres** [comment]
@nvisionative I thought the minimum requirements that Will is talking about are the DNN ones after selecting the DNN version. Not the requirements of nvQuickSite.

Example: User selects DNN 7.0. What are the minimum requirements for DNN 7.0? and so on..

**Comment by nvisionative** [comment]
@abukres my apologies- totally read the question out of context. :)

**Comment by david-poindexter** [comment]
Closing due to no community traction.  With the release of v2.0.0, contributions should be much easier due to massive refactoring and improvements in the codebase.
