### ISSUE TITLE
Problem with SQL Server on install of DNN

### ISSUE THREAD

**Issue by ac160006** [nvisionative/nvQuickSite#170]
![image](https://user-images.githubusercontent.com/294893/42729318-34192646-87a2-11e8-9c70-5f33d9b48af1.png)

![image](https://user-images.githubusercontent.com/294893/42729611-923dbf8a-87ab-11e8-8cf7-74350b1ea464.png)

The SSMS is running at this time.  
![image](https://user-images.githubusercontent.com/294893/42729619-dc94399c-87ab-11e8-97e3-5849bc85dfde.png)
I entered the password, "password" in order to change to the same password.  It seemed to be the correct password for SA.
Can I do a manual install process?  Any other ideas?

Thanks,
Andy
ac411@bellsouth.net

**Comment by abukres** [comment]
'SQLExpress' alone won't work. You should put machinename\SQLExpress or .\SQLExpress.

**Comment by ac160006** [comment]
Fixed that. Same problem!  Isn't there a manual install? Maybe can isolate problem.

**Comment by ac160006** [comment]
“can I install DNN without using nvQuickSite?”  Yes, that is what I mean.  I've tried the Microsoft's web platform installer and got the same errors.  So it is probably something to do with SQL Server, but I can't figure out what.  I'll try the step-by-step method, hopefully, in DNN docs somewhere.  Thanks for your help.

**Comment by nvisionative** [comment]
@ac160006 you are most likely correct, in that SQL Server must be setup correctly.  Are you following @abukres recommendation of using the **machinename\SQLExpress**?  In your case it appears this may be **DELL-INSPIRION-R\SQLExpress**.  If that doesn't work, then I would recommend checking the configuration to ensure Named Pipes and TCP/IP Connections are enabled.

1. Run SQL Server Configuration Manager.
2. Navigate to SQL Server Configuration Manager > SQL Server Network Configuration > Protocols for <machine instance>.
3. Double-click Named Pipes. ...
4. From Enabled, select Yes. ...
5. Double-click TCP/IP.
6. From Enabled, select Yes. ...

Save your configuration and try again with nvQuickSite.

**Comment by nvisionative** [comment]
We are doing some clean up of stale issues and will be closing this one.  However, please feel free to re-open if necessary.

**Comment by hamad2810** [comment]
same issue while installing nvqicksitev1.4.0
![error](https://user-images.githubusercontent.com/18468000/66734613-39d39100-ee7d-11e9-96b6-8b751e70ca26.PNG)

named pipes enabled
TCP/IP enabled
