### ISSUE TITLE
Indenting hosts file?

### ISSUE THREAD

**Issue by EPTamminga** [nvisionative/nvQuickSite#172]
The lines that are added to the hosts. file are indented.

That does not seem right to me?

![image](https://user-images.githubusercontent.com/5859855/43702707-df174d6a-995a-11e8-8070-7385d051e4d9.png)

**Comment by nvisionative** [comment]
@EPTamminga as long as each entry is on its own line, all is well.  Tabs were used simply for legibility and to to follow the examples provided in the HOSTS file.  It works either way.  Thanks.
