### ISSUE TITLE
Installation SQL error messages

### ISSUE THREAD

**Issue by KennethT101** [nvisionative/nvQuickSite#183]
Hi
**a shaggy dog story for you** on my using NVquicksite as a non-developer but literate computer user.  Having used DNN portals in various shapes and sizes for over 10 years (developers set them up for me), I have never once managed to install one. It always always failed on the SQL set up an so have I. On this occasion we were heading the same way. Using the standard DNN install 9x wizard, and following Chris Hammond's youtube videos (thank you btw), all was well until the install wizard SQL connect failed.  

Subsequently a thank you also to Michael Tobisch for pointing me to this forum.   

Carrying on, in the same way, the NVquick installer also failed with a long .net error message that was incomprehensible to me.

Thankfully, Michael unprompted had sent over the links to the system requirements page. So Winnie the Pooh style I went through each system requirement as a ticklist, and all the boxes indeed ticked. Almost accidentally at the bottom of the pages was the one liner that .net versions need integrated working.

So I took my sanity in my hands and entered the IIS world and noticed eventually that one of the .net versions was running 'classic' not 'integrated'. Found how to change it. Ran NVquicksite and would you believe it, a perfect install, then just like in the fairy stories the fastest DNN install I have ever seen.

This tool should be bundled into DNN as anyone like me could then install it. Perhaps a method to check IIS settings or system spec would be helpful as a pre install check.

However, a big thank you here as for the first time I can see a DNN default web site staring me in the face, and I did it*

Ken

* Ok with a chunk of software  and other people's skill to help me.

please make sure you have fulfilled all the necessary system requirements (https://github.com/nvisionative/nvQui...).

For problems with nvQuickSite please contact the nvisionative team and write an issue: https://github.com/nvisionative/nvQui...

**Comment by nvisionative** [comment]
@KennethT101 I am not sure how we missed this, but my sincere apologies for not responding sooner.  Thank you for sharing your story in such a creative, fun and helpful way.  We hope it will help others who may experience the same thing.

We do have plans to make ensuring minimum requirements for nvQuickSite much easier and more automated/user-friendly.  Our plans are to replace the current antiquated installer with a newer, more feature rich, installer.

We are performing some clean up of issues and will go ahead and close this one.  However, feel free to re-open if necessary.  Thanks again!
