### ISSUE TITLE
Add nvQuickSite to Chocolatey

### ISSUE THREAD

**Issue by jbrinkman** [nvisionative/nvQuickSite#184]
Chocolatey (https://chocolatey.org/) is a Package Manager for Windows apps that is useful for quickly re-installing apps when setting up a computer, or for easily upgrading installed applications.  Once you have all your apps installed, you can export a list of chocolatey installed packages which makes it trivial to setup another machine.  No more trying to remember what apps I had installed or what tool chain I need for development.  Just import the previously saved config file (keep it in onedrive, github, dropbox etc. for safekeeping) and let Chocolatey get everything installed while you enjoy a cup of coffee.

**Comment by bdukes** [comment]
See https://chocolatey.org/docs/create-packages for info on creating the package

**Comment by nvisionative** [comment]
@jbrinkman fantastic idea!  We'll take a look into this.  @bdukes thanks for the link!

**Comment by david-poindexter** [comment]
Closing this in favor of #258
