### ISSUE TITLE
Implement a CODE OF CONDUCT

### ISSUE THREAD

**Issue by nvisionative** [nvisionative/nvQuickSite#193]
Every healthy open source project needs a CODE OF CONDUCT and we do not currently have one.

**Comment by hismightiness** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/7d3e1551-d828-4ece-9814-d9e40af4d7b0-652e1797-ff34-4a49-95ae-344dce004f65-v1.png?transparent=1&palette=1&width=246)
