### ISSUE TITLE
nvQuickSite crashes and will not start

### ISSUE THREAD

**Issue by EPTamminga** [nvisionative/nvQuickSite#200]
I cannot start nvQUickSite anymore, the app crashes. I tried to build the app locally but I am missing too many references in the solution to get it to build.

Crash info in the Windows log:
```
Toepassing: nvQuickSite.exe
Framework-versie: v4.0.30319
Beschrijving: het proces is beëindigd als gevolg van een onverwerkte uitzondering.
Uitzonderingsinformatie: System.ArgumentException
   bij System.Version+VersionResult.SetFailure(ParseFailureKind, System.String)
   bij System.Version.TryParseVersion(System.String, VersionResult ByRef)
   bij System.Version.Parse(System.String)
   bij nvQuickSite.Main..ctor()
   bij nvQuickSite.Program.Main()
```
and

```
Naam van toepassing met fout: nvQuickSite.exe, versie: 1.2.0.0, tijdstempel: 0x5a9cac51
Naam van module met fout: KERNELBASE.dll, versie: 10.0.17763.404, tijdstempel: 0x2528b630
Uitzonderingscode: 0xe0434352
Foutmarge: 0x0000000000039129
Id van proces met fout: 0x2508
Starttijd van toepassing met fout: 0x01d4ee07d2e95558
Pad naar toepassing met fout: C:\Program Files (x86)\nvisionative\nvQuickSite\nvQuickSite.exe
Pad naar module met fout: C:\WINDOWS\System32\KERNELBASE.dll
Rapport-id: 7fa36814-d374-46fa-9304-4526413d7ec0
Volledige pakketnaam met fout: 
Relatieve toepassings-id van pakket met fout: 
```

Any suggestion what is wrong?

**Comment by ahoefling** [comment]
I tried using it today and I am seeing the same problem. Is there a backend server that supports nvQuickSite that is now down?

**Comment by nvisionative** [comment]
@EPTamminga thank you for reporting this and @ahoefling thank you for confirming.  We believe this is due to a restructuring of the GitHub project folder structure.  There is one thing nvQuickSite accesses on GitHub to obtain the latest version number.  The good news is this should be a quick fix.  😃

**Comment by nvisionative** [comment]
We are just waiting on Azure Build Pipeline to complete the build.  We'll merge the PR and immediately test.

**Comment by EPTamminga** [comment]
I finally got the debug build working, after a number of NuGet package updates., which included new versions of libraries. Now trying to use the build version.

**Comment by nvisionative** [comment]
Okay, this has now been resolved - thanks again for reporting it and we apologize for any inconvenience.

**Comment by ahoefling** [comment]
@nvisionative thanks for fixing this, I am confirming it works

**Comment by nvisionative** [comment]
@EPTamminga the current code base version is not in an acceptable state for use.  We are working on a new release (1.3.0).  In hindsight, we should be using a release branching strategy, but we are not.  😄  Please continue to use 1.2.0 until we officially release 1.3.0.  Thanks!

**Comment by nvisionative** [comment]
@ahoefling thanks for confirming version 1.2.0 this is indeed working fine again.

**Comment by EPTamminga** [comment]
@nvisionative OK, I have to rebuild my local version and use that? Or are you updating the release 1.2.0 in this repo?

**Comment by nvisionative** [comment]
@EPTamminga you can use the version 1.2.0 release that is published [HERE](https://github.com/nvisionative/nvQuickSite/releases/tag/v1.2.0).  You do not need to rebuild anything.  Just install/reinstall and use.

**Comment by EPTamminga** [comment]
@nvisionative: **Tnx.** 
I did not notice that the .msi file was replaced in the release. The new version works for me as well now.

**Comment by nvisionative** [comment]
@EPTamminga nothing got replaced.  The issue was not in the application itself, but rather something it was accessing.  :)  Please use the 1.2.0 release, as the current build of the repo is not ready for use.  Thanks.

**Comment by EPTamminga** [comment]
@nvisionate Ok, clear. It’s working for me, Thank you for your efforts.
