### ISSUE TITLE
Update INTERNET CURRENTLY UNAVAILABLE with a more informative exception message

### ISSUE THREAD

**Issue by skarpik** [nvisionative/nvQuickSite#213]
New install of nvQuickSite v 1.3 -- the software does not believe that I am attached to the Internet. Found this behaviour on two different computers (HP Omen workstation and Microsoft Surface Book).

Environment:
- Windows 10 Pro version 1809
- Windows Defender
- Malwarebytes v3.7.1

![nvquicksite error](https://user-images.githubusercontent.com/3846223/56096490-e1640c80-5eb6-11e9-9f8c-8915fc33a052.jpg)

**Comment by nvisionative** [comment]
@skarpik thank you for reporting this.  Most likely one of your anti-virus programs or firewall is blocking access to the GitHub API calls.  Can you temporarily disable them and see if nvQuickSite works?  Then it could be as simple as adding an exception.

**Comment by nvisionative** [comment]
FYI...this would not have been an issue in 1.2.0 and earlier, because it was not making GitHub API calls.  😉

**Comment by skarpik** [comment]
I turned off Malwarebytes -- no change. Turned off all the various flavours of firewall on Windows defender -- no change. I don't remember whether this showed up in an earlier version because I used nvQuickSite to install DNN 9.1.0 rc from a download. The message may have been there but I may very well have overlooked it since I didn't need to use the dropdown.

**Comment by skarpik** [comment]
I uninstalled version v1.3, reinstalled v1.2. Version 1.2 worked perfectly (I used it to install DNN v9.3.1). I don't know if this information clears things up or deepens the mystery.

**Comment by nvisionative** [comment]
@skarpik give us a day or two and we are going to generate a new build with some more detailed event/exception logging so we can try and get you up and running on v1.3+.  For now, you should be able to use 1.2.0 with no issues.

**Comment by skarpik** [comment]
Version 1.2 is perfect for me. When you have am updated version, I'm happy to test it on the computers that had issues.

**Comment by iJungleboy** [comment]
I just got a new laptop - installed 1.3 and have the same issue

**Comment by nvisionative** [comment]
@iJungleboy thanks so much for letting us know.  I think what we are going to do is a fairly quick maintenance release, 1.3.1.  In that release, we'll update the method that is throwing this currently hard-coded message (yeah, I know...not good) with a more informative exception message.  Hopefully, that will help us determine what is going on for you guys.
