### ISSUE TITLE
Resolve Error: Could not find part of path

### ISSUE THREAD

**Issue by iJungleboy** [nvisionative/nvQuickSite#219]
This is a follow up to #213 

I now get this message: 

![image](https://user-images.githubusercontent.com/5321186/56638450-8678a500-666e-11e9-8378-f6f6cd0ccf91.png)

Situation was that this is a new PC, installed nvQuickSite and first had the error #213, then got the newer release and now have this message. 

Note that I have these folders

```
C:\Program Files (x86)\nvisionative\nvQuickSite
```
but no subfolders underneath that.

**Comment by nvisionative** [comment]
@iJungleboy thanks for reporting this.  Can you manually create a `Downloads` folder and let us know what happens?  Now that we have a bit more detailed error message, hopefully we can isolate and correct the issue quickly for you and others that may be experiencing this. 

CC @skarpik

**Comment by iJungleboy** [comment]
Yes, creating the folder removes the error.

**Comment by nvisionative** [comment]
Thank you for the quick test @iJungleboy - we are looking into a potential fix now.

**Comment by nvisionative** [comment]
Good news - we have located the bug and will have a fix ready for a pull request shortly.  This warrants a 1.3.2 maintenance release.  Thanks so much for helping us isolate the issue!
