### ISSUE TITLE
Buttons not discoverable

### ISSUE THREAD

**Issue by iJungleboy** [nvisionative/nvQuickSite#220]
I just noticed that these things are buttons:

![image](https://user-images.githubusercontent.com/5321186/56662499-68c63280-66a4-11e9-823d-26d80cc18988.png)

But I would not have realized this, so I suggest to do something so it's clearer. Probably just creating tiles which aren't arranged so decoratively would help.

**Comment by nvisionative** [comment]
@iJungleboy thanks for letting us know your thoughts on this matter.  Currently, hovering over the tiles changes the cursor to the hand pointer.  We would be interested in hearing other's thoughts on this as well.

**Comment by iJungleboy** [comment]
So my main issue was that I never thought of hovering - since it looked so artistic I assumed it was just decoration.

**Comment by nvisionative** [comment]
Understood - thanks @iJungleboy - let's see if others chime in and have thoughts on this.  With this being an open source project, we did not go through any formal User Testing, so this may very well be a situation where the UI doesn't work like we thought it would.  :)

**Comment by bdukes** [comment]
It took me a while to figure out they were buttons, and I know a colleague had a similar surprise when I mentioned that they were clickable.
