### ISSUE TITLE
Can't install DNN 9.4.0 RC0

### ISSUE THREAD

**Issue by iJungleboy** [nvisionative/nvQuickSite#235]
Using nvQuicksite 1.4

Selecting the RC from the dropdown fails:

![image](https://user-images.githubusercontent.com/5321186/62693621-24e90600-b9d3-11e9-98b2-9d3a2e3d6c5c.png)

Selecting the RC from a local downloaded zip file also fails:
![image](https://user-images.githubusercontent.com/5321186/62693571-10a50900-b9d3-11e9-82ca-6b322fee0c77.png)

**Comment by david-poindexter** [comment]
@iJungleboy - the ZIP file on GitHub for 9.4.0-rc0 is corrupted.  Therefore, there is nothing that can be done from an nvQuickSite perspective.

**Comment by iJungleboy** [comment]
ok. thx. Did I somehow download the wrong one, or is there no functioning 9.4 RC out there?

**Comment by david-poindexter** [comment]
@iJungleboy the RC is technically fine, but something is awry with the ZIP.  Some ZIP utilities unzip it just fine.  Others result in an error.
