### ISSUE TITLE
Cleaning up after an install.

### ISSUE THREAD

**Issue by KenTombs** [nvisionative/nvQuickSite#236]
A month or six back, quicksite installed an experimental DNN site for us.  Did the job fine and about to use it again. Now with a 'home' portal being set up and server hardening is necessary, is there a clean-up list or tool to get rid of all but the essentials for a working portal install?

**Comment by david-poindexter** [comment]
@KenTombs I am not 100% clear on the question here, but I’ll try to address.  First of all, nvQuickSite only handles the “essentials” for getting a DNN instance running.  That said, it does NOT “harden” that instance.  That is beyond the feature scope of nvQuickSite.

To “clean up” (uninstall) an instance that was installed by nvQuickSite, following are the basic manual steps.

 - Reset (Restart) IIS
 - Delete the “Website” and “Logs” folders created by nvQuickSite
 - Delete the website in IIS Manager
 - Delete the dedicated Application Pool in IIS Manager
 - Delete the database via SQL Server Managment Studio
 - Delete the “Database” folder that nvQuickSite created
 - Remove entry for “127.0.0.1   <your domain name>” in ~/Windows/System32/drivers/etc/hosts

I hope this helps.
