### ISSUE TITLE
Add Community Website Link

### ISSUE THREAD

**Issue by hismightiness** [nvisionative/nvQuickSite#237]
Hopefully, the title is descriptive enough, but...

We need to add the official [DNN Community website](https://dnncommunity.org) link to the installer.

**Comment by david-poindexter** [comment]
Great request @hismightiness - we'll get this slated for the next release.

**Comment by david-poindexter** [comment]
Commenting so Mr. Stale will not auto-close this issue.  😆

**Comment by hismightiness** [comment]
I thought this was already done?

Sent from my T-Mobile 4G LTE Device

________________________________
