### ISSUE TITLE
Appearance dialog is blank 

### ISSUE THREAD

**Issue by georgeb1951** [nvisionative/nvQuickSite#238]
using nvQuicksite 1.4 dnn community 9.4 install runs without issue if I select default template.  go to pages - add a page - go to advanced for  that page and select appearance dialog is blank.  i'm not sure that this is an nvQuickstart issue but thought i's report as FYI

**Comment by david-poindexter** [comment]
Hi @georgeb1951 - what you are describing sounds like a possible **DNN Platform** issue.  **nvQuickSite** is just an installer.  If you are experiencing a DNN Platform issue once you have it installed, I would highly recommend reporting that at the [DNN Platform GitHub repo](https://github.com/dnnsoftware/Dnn.Platform/).  Thanks.  We will go ahead and close this issue.  Have a great weekend!
