### ISSUE TITLE
Add option to clean and reinstall

### ISSUE THREAD

**Issue by valadas** [nvisionative/nvQuickSite#239]
When testing Dnn releases, testers often have to delete the database and site to try a new install. Currently NvQuickSite really helps getting installed quick but if you want to cleanup and redo an install, you need to delete the database, the iis site (because it locks some files) and then the site folder.

nvQuickSite already has the option to optionally replace the IIS site if it already exists. It would be nice to have the same options for the files and the database (obviously turn off by default)

**Comment by david-poindexter** [comment]
@valadas this is already the way nvQuickSite works.  Yes, there is a checkbox for deleting the IIS site (if exists).  If that is checked the site name + file/folder location match an existing site, then it will prompt you with a warning that all related files/folders/etc. will be deleted by proceeding.  Hopefully, this clears things up, but let me know if you need additional clarification.

**Comment by valadas** [comment]
Hmm, I got an error on my side, but maybe it is related to some local permission issues on that drive... I will try again on another drive. Just to clarify, would this also replace the database with the same name ?

**Comment by david-poindexter** [comment]
@valadas I just re-tested this feature and I too received some errors on my first attempt.  I am not sure if it was due to me having a folder open in Windows Explorer or not, but upon closing Windows Explorer and re-attempting the same thing, it worked like a charm.

**Comment by valadas** [comment]
Ok, cool, I will retry on another drive and keep you posted...
