### ISSUE TITLE
Fails to Load in Certain Wifi Scenarios

### ISSUE THREAD

**Issue by hismightiness** [nvisionative/nvQuickSite#240]
The app doesn't load at all and no errors are displayed when the app fails to load under the following scenario:  

1. Get on a commercial airplane.  
2. Connect to wifi once it's available, but don't authenticate.  
3. Attempt to open nvQuickSite.  

## Expected Result  
The app loads as usual.

## Actual Result  
The app never loads and there is no indication as to why and/or what happened.  

## Error Details  
I found the following two errors in the Windows Event Log:  

Application: nvQuickSite.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.Version+VersionResult.SetFailure(ParseFailureKind, System.String)
   at System.Version.TryParseVersion(System.String, VersionResult ByRef)
   at System.Version.Parse(System.String)
   at nvQuickSite.Main..ctor()
   at nvQuickSite.Program.Main()  

Faulting application name: nvQuickSite.exe, version: 1.4.0.0, time stamp: 0x5ccf5602
Faulting module name: KERNELBASE.dll, version: 10.0.17763.802, time stamp: 0x86aa4cf5
Exception code: 0xe0434352
Fault offset: 0x0000000000039129
Faulting process id: 0x3020
Faulting application start time: 0x01d585223a4783e2
Faulting application path: C:\Program Files (x86)\nvisionative\nvQuickSite\nvQuickSite.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 53b0e006-165d-4971-b0c4-d6b266bf8e6e
Faulting package full name: 
Faulting package-relative application ID: 

## Suggested Fix(es)/Workaround(s)  
1. Set a timeout for checking for the version number.  If the timeout is reached, assume that there is either no or limited internet connectivity.  Instead of displaying the version number, maybe display an error icon that tells the end user that the version/release status was unable to be checked due to a poor/missing internet connection.  

2. Make the version/release check `async` to allow the app to load and for the internet error to occur more gracefully.  

3. Put something else here that I haven't thought about.  :)

**Comment by david-poindexter** [comment]
@hismightiness thanks for sharing this experience issue.  We'll see what we can do to make it better in a future release.

**Comment by Tychodewaard** [comment]
@hismightiness Are you certain that it has to do with the wifi? I just tried to launch nvquicksite at my office (130MBps) and I have the same issue. Not launching.
I am not really familiar with the Windows event log, so I did not find anything that points to a suspect. Might a Windows update have anything to do with it?

**Comment by david-poindexter** [comment]
stale bot - please keep this issue open.

**Comment by hismightiness** [comment]
Un-stale.  😄
