### ISSUE TITLE
Migrate on Azure VM

### ISSUE THREAD

**Issue by KenTombs** [nvisionative/nvQuickSite#242]
We are moving our current Azure Web Application Service DNN Portal (9.3) to an Azure VM (Server 2012). This is currently based on a 32 bit Web App service platform (dont ever use the Azure marketplace DNN installer), and so contains some 32 bit extensions.

Broadly the method:

The plan is to use Quicksite to condition the VM and install a fresh version of 9.3.

Then restore a straight copy of the current Portal over the fresh VM folders.

Then repoint to the current SQL database.

Will this approach 'probably' work?

thanks

**Comment by david-poindexter** [comment]
@KenTombs my apologies for missing this issue somehow.  If this is still a valid question, I think the answer would be "yes".  Although I have not had any experience with this approach in Azure specifically, we use this approach all the time for local development purposes.
