### ISSUE TITLE
Marked as Possible Ransomware

### ISSUE THREAD

**Issue by hismightiness** [nvisionative/nvQuickSite#244]
I've been using both software applications for a while now, so I was surprised to see the following issue.  For some reason, Acronis has identified nvQuickSite as potentially containing ransomware.  

Steps to Reproduce:

1. Run Windows 10.  
2. Install  nvQuickSite.  
3. Install Acronis True Image.  
4. Open nvQuickSite.  

Expected Behavior  
nvQuickSite would open and I could step through the wizard to install a new instance of DNN.  

Actual Behavior  
There was an unusual delay in the open/start-up time for nvQuickSite, and then the following images appeared.  I had to whitelist nvQuickSite to allow it to open.  

![image](https://user-images.githubusercontent.com/938023/79059391-423f3580-7c2e-11ea-84a6-89c977b4dd27.png)

![image](https://user-images.githubusercontent.com/938023/79059397-4cf9ca80-7c2e-11ea-8320-b4aa3dd88e6d.png)

![image](https://user-images.githubusercontent.com/938023/79059399-53884200-7c2e-11ea-8e75-f69c1392a78d.png)

![image](https://user-images.githubusercontent.com/938023/79059400-5b47e680-7c2e-11ea-866c-d6bec4e96dca.png)

**Comment by david-poindexter** [comment]
@hismightiness I can assure you there is no Ransomware in nvQuickSite.  Acronis most likely has a stance on applications by an "Unknown vendor".

**Comment by hismightiness** [comment]
I know there's no ransomware. That's not the point of the issue. The point is to find a way to not get flagged. Newbies may get freaked out if they see such a message.

Sent from my T-Mobile 4G LTE Device

________________________________
