### ISSUE TITLE
1.4.1 gets DNN install name wrong?

### ISSUE THREAD

**Issue by VashJuan** [nvisionative/nvQuickSite#252]
Just installed the latest, 1.4.1. Unblocked the installer ran it. Tried to click the Run as Administrator property, but it was greyed out (always on perhaps?!), then ran it on a current Win 10 Pro desktop. Here are the screenshots, but I think the installer package is just named wrong:
What's at 
C:\Program Files (x86)\nvisionative\nvQuickSite\Downloads\DNN_Platform_9.6.1-rc0001_Install.zip
and the installer is looking maybe for:
DNN_Platform_9.6.1-rc1_Install.zip though the full name is cut off by the dialog.
<img width="488" alt="5-10-2020 at 11 47 45 AM" src="https://user-images.githubusercontent.com/8594671/81507845-e7dcd780-92b4-11ea-90f6-17881a603feb.png">
This has happened twice.

Sorry to mess up your Mother's Day!

**Comment by VashJuan** [comment]
<img width="488" alt="5-10-2020 at 11 44 43 AM" src="https://user-images.githubusercontent.com/8594671/81507887-35f1db00-92b5-11ea-8bae-bae0726465db.png">

**Comment by VashJuan** [comment]
<img width="463" alt="5-10-2020 at 11 49 01 AM" src="https://user-images.githubusercontent.com/8594671/81507899-499d4180-92b5-11ea-84e1-8f0df2a511c6.png">

**Comment by david-poindexter** [comment]
@VashJuan thank you for reporting this.  I think we missed a few things in this release.  In fixing one issue, we created another!  😆  We'll work on a fix and try to get a new release out ASAP.

**Comment by VashJuan** [comment]
Oh the joys of software, right?!

I also saw this. I suspect it is not related, but it's also new for me.

<img width="488" alt="5-10-2020 at 11 58 42 AM" src="https://user-images.githubusercontent.com/8594671/81510151-8cb2e100-92c4-11ea-99f1-ce64cae242bf.png">

**Comment by david-poindexter** [comment]
Indeed!  😆 We'll have a new release shortly for this fix.

That "Set Folder Permissions" error is quite the annoying one and has been in existence in one form or another from the beginning.  The good news is it has no bearing (usually) on the results.
