### ISSUE TITLE
Option: reverse the installation?

### ISSUE THREAD

**Issue by EPTamminga** [nvisionative/nvQuickSite#256]
Is it an option to make nvQuickSite do the reverse: remove a complete installation?

Yes, I understand that that is a dangerous operation, but it would be very efficient in quickly removing testsites.

**Comment by david-poindexter** [comment]
@EPTamminga nvQuickSite already supports this in a slightly different way.  When you want to install a new instance, you can use the same directory and database.  nvQuickSite will replace them with a fresh new instance.  This is helpful for saving space.

**Comment by EPTamminga** [comment]
This is not what I suggested. 
Uninstall would mean: remove the DB, remove the folders, remove the site in IIS, remove the line in the host file.

**Comment by EPTamminga** [comment]
BTW I cannot reopen the issue... so it is up to you (@david-poindexter) to leave it closed.

**Comment by david-poindexter** [comment]
> This is not what I suggested. 
> Uninstall would mean: remove the DB, remove the folders, remove the site in IIS, remove the line in the host file. 

Yes, I understood perfectly what you were asking.  nvQuickSite does not support that exact scenario.  

I'll re-open the issue if you'd like, but I think in order for it to gain traction for someone to contribute a solution, a bit more work would need to be done to define the expected UI/UX.  

Thanks for the suggestion @EPTamminga.

**Comment by hismightiness** [comment]
This is an interesting suggestion.  I probably create no less than 3 test sites per day for support alone.  When I know that one is invalid/old, I just overwrite it though, as David suggests.  I like the idea of being able to bulk uninstall all or a selection of sites created by nvQuickSite.
