### ISSUE TITLE
Save username for SQL Server Authentication

### ISSUE THREAD

**Issue by EPTamminga** [nvisionative/nvQuickSite#257]
Can the DB user/pw also be saved in the settings?

![image](https://user-images.githubusercontent.com/5859855/81908168-26320980-95c9-11ea-938d-3c8f174dfdcd.png)

This is especially useful for testsites, where the same DB user/pw is used

**Comment by EPTamminga** [comment]
Still valid

**Comment by david-poindexter** [comment]
@EPTamminga I am thinking this would be a a pretty big security concern, so I would personally not be in favor of this (especially considering how this information would be saved).  Let's see what others say and go from there.  

By the way, is there any reason you don't use Windows Authentication instead?

**Comment by EPTamminga** [comment]
Make the PW hidden (****) in display?

All my/our sites have a user/pw, just a habit...

**Comment by david-poindexter** [comment]
@EPTamminga the display of the password in the UI is not the issue I am referring to (though that should be **** - this would make a great new issue by the way 😄 👍 ).  I am talking about where and how these items are stored for future use in the app.  There may be a way to make that more secure though.  Let me give it some thought.  Thanks for talking it through.

**Comment by EPTamminga** [comment]
I know that the problem is storing it safely, but still be able to retrieve it. MB only the username should be stored, and the PW always to be entered.

**Comment by david-poindexter** [comment]
Okay, that is a nice compromise and I think we can definitely get behind that approach.  Thanks @EPTamminga!

**Comment by hismightiness** [comment]
I think this is still valid.  It's got my 👍  :)

**Comment by david-poindexter** [comment]
@EPTamminga @hismightiness @valadas @donker and anyone else that may use the SQL Server Authentication option, I started digging deep into this and this is honestly super easy.  However, I ran into some unexpected behavior while testing.  Before I invest too much time into "fixing" all the "issues" I discovered (which go way beyond this issue), I wanted to ask a few questions to validate the desired behavior for using SQL Server Authentication.

1. Do you want the SQL Server Authentication User Name to automatically match the Site Name like it currently does with the install subfolder and database name (with the ability to override it)?  Or do you want it to just "stick" and remember what you used during the last use?
2. Are you expecting the SQL Server Authentication User Name to be the user that is ultimately used in the web.config for DNN?
3. Are you expecting the SQL Server Authentication User Name to be the user that drops the database (if applicable), creates the database, and sets database permissions?

My thoughts are, the current implementation is incomplete, quite broken and honestly always has been.  The good news is...it can be fixed.  😉  We just need to agree on the expected and behavior.  I'll try to articulate the way I think it should work having given this considerable thought.

The SQL Server Authentication User Name entered should...
* ...not be the user that drops the database, creates the database, or sets database permissions.  These actions should be done via Windows Authentication.
* ...be added as a login to SQL Server if it doesn't already exist.
* ...be checked to ensure the password entered is correct (a connection can be established using entered credentials) if the login already exists.  If not, prompt the user that the User Name entered already exists and that the Password entered should match.
* ...be a user that has been granted access to the database created.
* ...be a user with the appropriate permissions (dbowner) for the database created.

Thoughts?

**Comment by hismightiness** [comment]
The suggested scenarios/updates here make me think that this Issue is being suggested in order to use this beyond local development scenarios.  In my opinion, that would be dangerous and should be considered completely, as it brings with it a higher level of responsibility and a much larger number of support use cases.  Most developers don't need much more than using a single user or Windows Authentication.  Only in deployment scenarios does it make sense to support a user account per site.  Just my $0.02.

**Comment by valadas** [comment]
Yeah, I agree with all of this. I honestly never used nvQuickSite for production and never even tried sql server authentiction on it. That beeing said, if that is a supported scenario, the suggestion in the original post makes sense to me. I would not however remember the password between runs...

**Comment by david-poindexter** [comment]
> The suggested scenarios/updates here make me think that this Issue is being suggested in order to use this beyond local development scenarios.  In my opinion, that would be dangerous and should be considered completely, as it brings with it a higher level of responsibility and a much larger number of support use cases.  Most developers don't need much more than using a single user or Windows Authentication.  Only in deployment scenarios does it make sense to support a user account per site.  Just my $0.02.  

The goal is NOT to support production use.  You bring a good point.  Perhaps a login with `dbowner` rights on the database is sufficient.

**Comment by sleupold** [comment]
I strongly suggest using Integrated Security (for testing AND production).
The only use case for SQL Server Authentication should be a Scenario, where SQL Server/Cluster resides on a separate machine outside the domain, the web server is part of.

**Comment by david-poindexter** [comment]
Based on the feedback received, we will not be creating any SQL logins or users for the entered SQL Server Authentication User Name and Password.  It will be assumed that such a user name being entered has already been created in the local development environment with the appropriate permissions needed.

Also, we will not try to match the User Name with the Site Name.  We'll simply "remember" the User Name last used.

Thanks for the quick feedback everyone!

**Comment by sleupold** [comment]
plase allow as well using integrated security instead

**Comment by david-poindexter** [comment]
> plase allow as well using integrated security instead

@sleupold that option has been in nvQuickSite since day one and is what is believed to be used by most everyone.  😉
