### ISSUE TITLE
Deploy New Site to Azure

### ISSUE THREAD

**Issue by VashJuan** [nvisionative/nvQuickSite#285]
Maybe this is better done via providing a package to Azure (as DNN Corp has done), but it would be nice none-the-less to be able to deploy the latest & greatest!

**Comment by david-poindexter** [comment]
@VashJuan thanks for the idea.  nvQuickSite is a tool intended for the installation of DNN in a local environment for development, testing, quality assurance, playground, etc.  We do not recommend using it within production environments.

Something like this would be best published as an official package within that environment.
