### ISSUE TITLE
Installer can't find file

### ISSUE THREAD

**Issue by leigh-pointer** [nvisionative/nvQuickSite#299]
![image](https://user-images.githubusercontent.com/9447612/100080919-b38eca00-2e46-11eb-9e9b-ab5b399fe7a6.png)

Downloading and running the setup file an 'Ok' dialog is displayed and the product is not installed.
.

**Comment by david-poindexter** [comment]
I think maybe something went awry during the installer creation.  I’ll create a new installer and upload as soon as possible.  Thanks.

**Comment by david-poindexter** [comment]
@leigh-pointer did you happen to uninstall a previous version first?

**Comment by leigh-pointer** [comment]
Hi David,
This was a fresh install on a new windows installation.

**Comment by david-poindexter** [comment]
Okay, thanks @leigh-pointer.  We are still trying to figure out what went wrong with the installer.  For the interim, as a workaround, I think you can install v1.4.2 and then upgrade it to v2.0.0.

**Comment by leigh-pointer** [comment]
I have just tried that and, as work around that works great. 
BTW, Thank you for a brilliant product.  Seriously would be lost without it!

**Comment by david-poindexter** [comment]
That is GREAT news!  Thanks for confirming.  This will help some others that are seeing this behavior.

And you are most welcome - by the community for the community!  But we won't complain with a coffee sponsorship - haha!  🤣☕️
