### ISSUE TITLE
Change text Cancel to Close

### ISSUE THREAD

**Issue by EPTamminga** [nvisionative/nvQuickSite#311]
I love the remove Existing Sites option. Shouldn't the button be named **Close** and not **Cancel**?

![image](https://user-images.githubusercontent.com/5859855/100585204-79617480-32ed-11eb-86a2-e33ab9b105a7.png)

**Comment by david-poindexter** [comment]
@EPTamminga glad you are pleased with the new delete site feature!

We can go ahead and plan to make the suggested change for the button name.  Thanks.
