### ISSUE TITLE
Change control name for close button on Delete Site form

### ISSUE THREAD

**Issue by david-poindexter** [nvisionative/nvQuickSite#313]
Currently, the control name for the close button is the default injected by Visual Studio.  It needs to be updated to something more meaningful for the action in which it is associated (e.g., `btnClose`).

**Comment by warcrime96** [comment]
hello david can i do it?

**Comment by david-poindexter** [comment]
@warcrime96 PRs are always welcomed for this project!

**Comment by warcrime96** [comment]
Can you guide me a little bit,first time contributor ,name the code part tha that need changing it's a huge project and i am kinda lost here but i will do it!

**Comment by valadas** [comment]
That control name is in a couple of places and it would need to be renamed using the visual editor to cover them all, but it would be in this file: https://github.com/nvisionative/nvQuickSite/blob/41494e3a0baba7fe443cd37c83ecc880fbf9ec46/nvQuickSite/Controls/Sites/ViewExistingSites.Designer.cs#L69

**Comment by david-poindexter** [comment]
Awesome @warcrime96 - the thing I will reiterate here is that to avoid potential issues, the button name needs to be changed in the form designer rather than directly in close (unless you really know what you are doing in there) as the `*.Designer.cs` files are auto-generated.  So I would just recommend renaming the button in the Properties window of the form designer from `metroButton2` to something like `btnClose`.  Thanks!

**Comment by warcrime96** [comment]
i think i switched it , did it merge?

**Comment by david-poindexter** [comment]
> i think i switched it , did it merge?

I am not quite sure what you mean.  I am not seeing any pending pull request, but will happily review if you submit one.  Thanks!

**Comment by warcrime96** [comment]
im trying to make a pull request ,or push from intelij but gettin denied
can u quide me?

Στις Σάβ, 20 Φεβ 2021 στις 10:26 μ.μ., ο/η David Poindexter <
notifications@github.com> έγραψε:

**Comment by warcrime96** [comment]
It keep rejecting the pull request ,i am ready to commit though,i think i successfully made the needed changes

**Comment by david-poindexter** [comment]
@warcrime96 it looks like this is your branch:  
https://github.com/warcrime96/nvQuickSite/tree/patch-1

If that is correct, you would go here to create a pull request:
https://github.com/warcrime96/nvQuickSite/pull/new/patch-1

That said, it does not look like [the directions here](https://github.com/nvisionative/nvQuickSite/issues/313#issuecomment-778366829) were followed.  You will need to update the control name via the Visual Designer in Visual Studio.  That will automatically generate the necessary updates to the designer file.  Just change the one line of code in your branch will not be sufficient.

Thanks!
