### ISSUE TITLE
Error with setting folder permissions

### ISSUE THREAD

**Issue by EPTamminga** [nvisionative/nvQuickSite#314]
The error message is not completely visible and I cannot continue:
 
![image](https://user-images.githubusercontent.com/5859855/102009955-2d75ed00-3d3b-11eb-9969-a0d22b13af7b.png)

## Previous version

In a previous version (1.4.2), the error was also visible, but **I can continue** and I get a correct installation:

![image](https://user-images.githubusercontent.com/5859855/102009984-5bf3c800-3d3b-11eb-854e-215994e2c8df.png)

**Comment by valadas** [comment]
One possible cause is a change where not all files where deleted, the file replacement logic has changed a bit to also delete hidden files (for example a .git directory).

I had this issue happen to me and it was because the folder was open. Can you try to make sure the folder is not open and try again just to confirm that theory ?

**Comment by EPTamminga** [comment]
The folder where the new site must go, did not exist, I create a new install in a new (sub)folder of an existing main folder.
The old version continued after the warning/error message, version 2.1 does not continue.

**Comment by david-poindexter** [comment]
@EPTamminga perhaps you could check the logs using the new logging features (see nvQuickSite Settings to set the desired level of login).  You may be able to ascertain more helpful information there to help resolve the issue.

**Comment by skrantzman** [comment]
I am having the same issue.  Went to the logs folder but there wern't any logs.  I don't think this is a folder permissions issue (atleast not for me), as the message says. If I look at the security properties of the website folder, I see that the app pool user was added and given Modify permission. 

I was haveing SQL issues earlier on this PC, so I changed the Database Server Name from (local) to MyPcName\SQLEXPRESS, and the installation proceeded just fine.  So for me it looks more like a database connectivity issue than a folder permission issue.

**Comment by david-poindexter** [comment]
@skrantzman the logs I am referring to are the nvQuickSite logs (which are in Program Files folder where nvQuickSite was installed), not the IIS `Logs` folder that nvQuickSite creates for a website.

**Comment by valadas** [comment]
In other words, you can go to nvQuickSite settings and you will see an option for the logs level, if you set that higher (like debug or verbose) then try the operation it will log details about the error. To get to the logs folder there is also an icon that will open the right folder in Explorer right next to where you select the logging level.

**Comment by david-poindexter** [comment]
Thank you for pointing that out @valadas - I forgot there was a link right there to open the logs!  😆

**Comment by skrantzman** [comment]
Thanks for pointing out the log settings and location.
Here is the error when using (local) for the DB Server Name.

`[ERR] Error occured while attempting to set folder permissions
System.Security.Principal.IdentityNotMappedException: Some or all identity references could not be translated.
   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)
   at System.Security.Principal.NTAccount.Translate(Type targetType)
   at System.Security.AccessControl.CommonObjectSecurity.ModifyAccess(AccessControlModification modification, AccessRule rule, Boolean& modified)
   at System.Security.AccessControl.ObjectSecurity.ModifyAccessRule(AccessControlModification modification, AccessRule rule, Boolean& modified)
   at nvQuickSite.Controllers.FileSystemController.SetFolderPermission(String accountName, String folderPath)`

So how does changing the DB Server Name from (local) to MyPcName\SQLEXPRESS, or .\SQLEXPRESS have any effect on folder permissions?

**Comment by valadas** [comment]
Hmm, maybe it is not related to the database at all... Some other form of permission issues maybe...
In my case the only time it happened was because the folder was open in Explorer.
It may sound stupid, but if you restart and try again, does it work?

**Comment by valadas** [comment]
Also, not sure if maybe anti-virus might block this... If you do use one, can you try pausing it and testing

**Comment by skrantzman** [comment]
Daniel,
turning off virus protection did not help. Rebooted too with no success.

I made sure that SQL is configured to allow localhost access through port 1433. In SSMS I can connect using localhost, MyPcName, .\SQLEXPRESS, and MyPcName\SQLEXPRESS. However in nvQuickStie I can only get past the Database step if I use MyPcName\SQLEXPRESS or .\SQLEXPRESS. Logically, to me anyway, it points to having to do with the way nvQuickSite is connecting to the database, as why else is it successful if I use the server\database_name syntax, but not if I use (local).

I am fine with the workaround, as I am just glad I got it to work.  I just think it's a little curious is all.

**Comment by EPTamminga** [comment]
@valadas Interesting finding: if I set the log level to more than the default `Information `(so `Debug `or `Verbose`), there is no error displayed and the install continues.
If I start again and leave confirm the log level to Information, the error reappears..

I include the log files
[log-20201215_001.txt](https://github.com/nvisionative/nvQuickSite/files/5694323/log-20201215_001.txt)

**Comment by skrantzman** [comment]
So I tried to see if EPTamminga's workaround would work on my system.  In short no, I still have to change my DB Server Name. So I compared the ERR in my logs with his, and they are exactly the same error message. Now the question is: Is although it is the same error message, is it the same cause?  The mystery deepens.

**Comment by david-poindexter** [comment]
@skrantzman and/or @EPTamminga this one is a bit hard to isolate for us when we can't recreate the issue.  Perhaps we can schedule a meeting to screen share and debug the source on one or both of your machines.  Let us know if this is of interest.

By the way, I created a separate issue to look into text wrapping for the message dialogs.

**Comment by EPTamminga** [comment]
@david-poindexter I understand that it is difficult to cover if it is not reproducible on your side.
I will clone the repo and see if I can do a build myself. If so, and If I can allocate an hour or so I can do the debugging myself.  
That seems easier for me than a web meeting...

**Comment by david-poindexter** [comment]
Excellent - thank you @EPTamminga - working with this project should be so much easier now with the refactor.  It should be much more obvious what is happening where.

**Comment by EPTamminga** [comment]
Debugging code from others is always less obvious than debugging your own code 😃

**Comment by skrantzman** [comment]
@david-poindexter, 
Last night I started doing just that.  The problem for me resides on lines 371 - 381 of the FileSystemController.cs file.
```C#        
371    private static string GetDBServiceAccount(string dbInstanceName)
372            {
373                string dbServiceAccount = @"NT Service\MSSQLSERVER";
374    
375                if (dbInstanceName.IndexOf(@"\", StringComparison.OrdinalIgnoreCase) > -1)
376                {
377                   dbServiceAccount = @"NT Service\MSSQL$" + dbInstanceName.Substring(dbInstanceName.LastIndexOf(@"\", StringComparison.OrdinalIgnoreCase) + 1).ToUpperInvariant();
378                }
379    
380                return dbServiceAccount;
381            }
```
When using (local) for Database Server Name in nvQuickSite, the dbServiceAccount variable is set to NT Service\MSSQLSERVER. Because the following IF condition is not met ( (local) does not contain a \\), the variable stays set as is.  Running `get-service | foreach {Write-Host NT Service\$($_.Name)}` in PowerShell, I can see that the NT Service\MSSQLSERVER account does not exist on my system. Because the account does not exist, line 183 ` SetFolderPermission(dbServiceAccount, logsDir);` breaks the code.  

I believe that doing some error checking to see if the NT Service\MSSQLSERVER account exists before trying to use it is in order. If it doesn't exist we can throw a more specific error.

**Comment by EPTamminga** [comment]
@david-poindexter 
I tried to reproduce the error consistently, so I can debug and find the problem, but... I was unable to do so. I could not find a combination of names and settings that would reproduce the error every time. I got the error several times, but what triggered the error was is unclear to me.

What I did experience was that moving back and forth between the screens `Site Info` and `Database info`, and check or uncheck the `Delete Site in IIS (if exist)`, seem to influence the error trigger, but I could not find a sequence that produced the error consistently.

Another thing that I found was that the `Site delete function `did not remove the Database folder and also did not remove the log folder of the site.

**Comment by david-poindexter** [comment]
@EPTamminga okay, I think you may be on to something there.  Going back and forth between tabs would probably result in less than desirable outcome.  This is certainly an area that could be improved.

**Comment by ainsofs** [comment]
I had this issue. It was complaining about folder permissions. I went back one step and then forward again where the system prompted that a folder existed and if I wanted to delete. When I let it delete the folder. It was able to go to the next step without permissions errors. 

FYI the initial folder was created by the tool.
