### ISSUE TITLE
Problem setting folder permissions for path...

### ISSUE THREAD

**Issue by VashJuan** [nvisionative/nvQuickSite#320]
New Win 10 Pro laptop. Enabled IIS in Windows Features. Installed & ran NVQuickSite today. All goes well until I go past this screen & get the following error.
![5-22-2021 at 3 38 45 PM](https://user-images.githubusercontent.com/8594671/119243600-1e327100-bb1d-11eb-9ffa-0e630e9714f8.png)

I suspect it is because I had not installed SQL Server Express (do you check for that?!), but now that I have I still get that. I hadn't created the root directory (c:\Sites), so you did with whatever permissions defaulted to I guess. The local apppool does have Write permissions.

Other ideas?

**Comment by david-poindexter** [comment]
@VashJuan hi - thanks for using `nvQuickSite`.  I would recommend going into settings and changing the level of logging and view the logs.  That should help isolate the error you are experiencing.

**Comment by VashJuan** [comment]
Thanks David!

I just started over & rebooted & used a new website name & I think the last item got it through the end. Cool!

HOWEVER (always!), I now get 

HTTP Error 500.19 - Internal Server Error
Error Code | 0x80070021
 when visiting the site. The <Handlers> line in web.config is highlighted.

Curses.

So looking that up leads to 
https://docs.microsoft.com/en-us/iis/get-started/planning-for-security/how-to-use-locking-in-iis-configuration

which leads me to edit
%windir%\system32\inetsrv\config\applicationHost.config

from:
<section name="handlers" overrideModeDefault="Deny" />
section name="modules" allowDefinition="MachineToApplication" overrideModeDefault="Deny" />

Which then gets me to:
HTTP Error 500.21 - Internal Server Error
Error Code | 0x8007000d

500.21 is - Module not recognized.
specifically:
Handler "ExtensionlessUrl-Integrated-4.0" has a bad module "ManagedPipelineHandler" in its module list

Hmmm, sounds like a project for another day...

**Comment by david-poindexter** [comment]
@VashJuan several things for you to check.

1. Check to ensure you have IIS set up and configured correctly.  You may find [this blog post helpful](https://www.dnnsoftware.com/community-blog/cid/155489/iis-gotchas-when-installing-dnn).  
2. Sometimes anti-virus software can get in the way and may need to be configured differently.  To help rule this out, you may want to try temporarily disabling it and trying a new install using nvQuickSite.

**Comment by VashJuan** [comment]
Bingo. I turned on a few items from the blog referenced above and it works!. I didn't track exactly which ones (of course, sorry) but ASP.NET 3.5 was NOT required.

Thx David!

**Comment by david-poindexter** [comment]
Excellent - I am glad you got it figured out!
