### ISSUE TITLE
Sort versions by version instead of alphabetically

### ISSUE THREAD

**Issue by valadas** [nvisionative/nvQuickSite#323]
Recently @EPTamminga reported on slack that the versions are not ordered by numbers.

I would be a nice improvement if we could cast the value to a `Version` object and sort it by version instead of just alphabetically before populating that dropdown.

**Comment by valadas** [comment]
The `Version` class even has built-in methods for that.

```
var versions = new List<Version>{
    new Version("1.10.0"),
    new Version("1.2.3"),
};
versions.Sort();
```

This would sort them properly (1.10.0 after 1.2.3) and then we feed that sorted list into the dropdown.

**Comment by david-poindexter** [comment]
Sounds great to me!

**Comment by jeremy-farrance** [comment]
I had made a visual before I realized someone already posted the problem and solution. :)

![image](https://user-images.githubusercontent.com/653301/129973944-9ade95c7-008e-49d1-8954-48dedbbd2bbf.png)

**Comment by hismightiness** [comment]
I kind of like it the way it is... It's more exciting, like an easter egg hunt.  ;)
