### ISSUE TITLE
Error deleting multiple websites

### ISSUE THREAD

**Issue by skarpik** [nvisionative/nvQuickSite#350]
nvQuickSite version: 2.1.2
OS: Windows 10 Pro

While deleting a number of websites, I came upon a problem. The first website deletes OK but deleting a second website causes an error (see jpeg below). By closing nvQuickSite, reopening and starting the deletion process again, the deletion finishes up correctly. 

I suspect what is happening is that when nvQuickSite modifies the hosts file in the process of deleting the first web site, it does not close the hosts file. Then when it is trying to open the hosts file to delete the entry corresponding to the second website, it can't open the hosts file because it is already open.

![nvQuickSite Error](https://user-images.githubusercontent.com/3846223/145533214-68ec4d7d-ec11-4994-b8d3-0497c75cc635.jpg)

**Comment by david-poindexter** [comment]
@skarpik I had a similar issue to this and discovered it was my Antivirus software (Kaspersky) that needed a rule to allow access to this file.  Perhaps that is what you are running into?  If you search the issues here for `Kaspersky` you should find details on how I resolved it.

**Comment by david-poindexter** [comment]
See #171
