### ISSUE TITLE
Accommodation for SQL Express Named Instance

### ISSUE THREAD

**Issue by skrantzman** [nvisionative/nvQuickSite#352]
Hey David, more of a question than an issue.

When someone installs SQL Server Express, there are two options, Default (MSSQLSERVER), and Named (SQLEXPRESS).  One would think that during an install, Default would be the selected option, but in Microsoft's infinite wisdom, they chose to make Named the default option instead of Default. Really kind of funny if you ask me, but if your not paying attention and breeze through that step, your SQL instance is now called SQLEXPRESS.

This obviously causes permission issues when trying to install a DNN site using nvQucikSite and keeping (local) as the Database Server Name.  However switching it to .\SQLEXPRESS  resolves the  problem with setting folder permissions. For someone new to nvQuickSite, who is not aware of this subtlety, this could be confusing and lead to frustration and them giving up on nvQuickSite.

I was wondering if it would be possible, when (local) is set, to programmatically check to see if MSSQLSERVER is the name SQL instance, and if so continue as MSSQLSERVER, and if it is not to check if SQLEXPRESS is set as the named instance, if so continue as SQLEXPRESS, if not then throw the error message.

Could really be a benefit to newbies.  Just a thought, as I ran into this problem after setting up a new PC and forgetting to change the option from Named to Default when installing SQL Server Express (yes I know, I probably should be using SQL  Server Developer edition.)

**Comment by david-poindexter** [comment]
@skrantzman thank you for posting this.  It certainly gives me an idea as to how to improve the user experience.  We'll leave this issue open to track progress.
