### ISSUE TITLE
Admin Rights?

### ISSUE THREAD

**Issue by leedavi** [nvisionative/nvQuickSite#354]
The code here forces Admin rights...

https://github.com/nvisionative/nvQuickSite/blob/41494e3a0baba7fe443cd37c83ecc880fbf9ec46/nvQuickSite/Program.cs#L54-L74

But when I start the program on one of our servers (as administrator user) nvQuick does not have the rights to add permissions and I do not get a message.
 
If I purposely "Run as Administrator" it works.

This is no problem, unless I forget to run as administrator,

**Comment by david-poindexter** [comment]
@leedavi can you do us a favor here and do the following?

* Run nvQuickSite as administrator (manually)
* Go into the `nvQuickSite Settings`
* Change the logging level to `Verbose`
* Save
* Close nvQuickSite
* Relaunch nvQuickSite (without manually running as administrator)
* Got back into `nvQuickSite Settings`
* Click `View Logs`
* Find log file for the current day and search for the applicable log entries
* Share via this issue

From there, hopefully, we can gain a clue as to what is going on.

Thanks!

**Comment by leedavi** [comment]
Hi David.  True to form... it worked this time.

I do see this in the original logs...

2022-02-09 16:10:20.595 +01:00 [ERR] Error occured while attempting to set permissions for IIS APPPOOL\catalog.rockettest.me_nvQuickSite on folder C:\NEVOWEB\WebsiteBuild\catalog.rockettest.me\Website
System.Security.Principal.IdentityNotMappedException: Some or all identity references could not be translated.
   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)
   at System.Security.Principal.NTAccount.Translate(Type targetType)
   at System.Security.AccessControl.CommonObjectSecurity.ModifyAccess(AccessControlModification modification, AccessRule rule, Boolean& modified)
   at System.Security.AccessControl.ObjectSecurity.ModifyAccessRule(AccessControlModification modification, AccessRule rule, Boolean& modified)
   at nvQuickSite.Controllers.FileSystemController.SetFolderPermission(String accountName, String folderPath)

**Comment by david-poindexter** [comment]
What version of nvQuickSite are you running?  Is it the latest release?  This seems to be a different issue altogether that has been resolved in a later release.

**Comment by david-poindexter** [comment]
This is the latest release, 2.1.2 - https://github.com/nvisionative/nvQuickSite/releases/tag/v2.1.2

**Comment by leedavi** [comment]
It is 2.1.2.  I send you the logs by email.

**Comment by david-poindexter** [comment]
Interesting.  I honestly do not know why you are experiencing what you are experiencing.  I am unable to reproduce the issue.  We could try to get on a Zoom some day and I can add some more logging to see if we can narrow it down, but I think the quick solution to your specific use case is to do the following:

* Pin nvQuickSite to your taskbar
* Right-click on pinned nvQuickSite app and go to Properties
* Choose Advanced
* Click the "Run As Administrator" checkbox
* Save

Now from this point on running nvQuickSite will run as administrator if you click the app in your taskbar.  Let me know if this works for you!

**Comment by leedavi** [comment]
Yes, I don't think it's worth the time to chase this.

Like I said "Run as Administrator" always seems to work.

Maybe a clash with our security setup, but it's not a problem.  I thought I'd let you know in case anyone else experiences this.

**Comment by david-poindexter** [comment]
Thanks so much for posting this here just in case anyone else is experiencing it.  We are happy to reopen and investigate it further should the need arise.  Cheers mate!
