### ISSUE TITLE
Duplication of version in dropdoen

### ISSUE THREAD

**Issue by leedavi** [nvisionative/nvQuickSite#355]
The dropdown for version has duplicate versions.   Each time nvQuickSite is opened there seems to be another duplicate added.

![image](https://user-images.githubusercontent.com/5583141/163398880-871289c2-d557-457f-8ee7-de35ef7c04d4.png)

**Comment by david-poindexter** [comment]
@leedavi this issue was resolved a while back.  Have you upgraded to the latest version of nvQuickSite?

**Comment by leedavi** [comment]
Wow.. very Sorry David. I totally zapped the big green button!!  I thought I was on the latest version.

I've upgrade and it's all OK.

P.S. When I download from GitHub I get some very seriously loud "DO NOT RUN" messages form windows.

**Comment by david-poindexter** [comment]
No worries mate - just glad you got it sorted!
