### ISSUE TITLE
Error with permissions

### ISSUE THREAD

**Issue by jldelatorre** [nvisionative/nvQuickSite#356]
Hi everyone. I stumbled with this error in the final step for installing DNN. It seems to be a permissions problem. And tried by open nvQuickSite as administrator and get the same result.

![nvquickError](https://user-images.githubusercontent.com/81640907/175109720-110bcfe6-e649-4fa9-920e-57a62a3f9766.png)

**Comment by WillStrohl** [comment]
Hey @david-poindexter ...  I took a quick look at this myself and didn't notice anything obvious.  Do you know of any quick troubleshooting steps we can take to resolve this for @jldelatorre?

**Comment by david-poindexter** [comment]
@jldelatorre this is quite the common error people experience from time to time with nvQuickSite and there are many reasons this can happen.  As a first step, I recommend going into nvquickSite Settings and enabling Verbose logging.  Re-run the installation attempt and review the logs to see if there is more insight on what may be causing the issue.

**Comment by jldelatorre** [comment]
@david-poindexter thanks for the feedback. I enabled the verbose login and run to the same error. Here is the complete error log:
2022-06-22 15:44:23.422 -04:00 [ERR] Error occured while attempting to set permissions for NT Service\MSSQLSERVER on folder D:\Web\NvQuick\testsite\Database
System.Security.Principal.IdentityNotMappedException: Some or all identity references could not be translated.
   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)
   at System.Security.Principal.NTAccount.Translate(Type targetType)
   at System.Security.AccessControl.CommonObjectSecurity.ModifyAccess(AccessControlModification modification, AccessRule rule, Boolean& modified)
   at System.Security.AccessControl.ObjectSecurity.ModifyAccessRule(AccessControlModification modification, AccessRule rule, Boolean& modified)
   at nvQuickSite.Controllers.FileSystemController.SetFolderPermission(String accountName, String folderPath)

**Comment by WillStrohl** [comment]
I'm trying to get the entire log from @jldelatorre .  In the meantime, please know this is happening on an AWS WorkSpace - but we have other WorkSpaces that don't have this issue.  This is the only one.  So, it might simply be a configuration issue.  If we find the resolution, we'll post it here.  

If anyone else has a potential fix in the meantime, we'd appreciate any suggestions.  :)

**Comment by david-poindexter** [comment]
@jldelatorre and @WillStrohl are you using a named instance for MSSQL server or are you trying to use something like `(local)`.  If you have multiple SQL Server instances, you may need to ensure you are using a named instance.

**Comment by david-poindexter** [comment]
Oh, and just one more idea.  Are you using Kaspersky by chance?  If so, perhaps try temporarily disabling it during the installation to see if it is perhaps intercepting some action.  I randomly run into this issue despite putting exceptions in place within Kaspersky config.

**Comment by WillStrohl** [comment]
Good question, David.  In this case, Kaspersky wouldn't be getting in the way.  The computer in question only has Microsoft Defender on it, I believe.  

I've looked at the log file myself.  I don't see much at first glance, except the database folder permission error already pasted and the one mentioned below.  In the case of the permissions error that is keeping us from using this, it happens what appears to be more than a dozen times in the log, but with nothing useful I could see before and after each instance.  

The other error I see happening over and over is below.  This one is odd to me, because the computer has no issues reaching the internet for any other purpose.  

```  
2022-06-22 15:44:04.524 -04:00 [ERR] Unexpected error occurred retrieving remote packages.
System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at nvQuickSite.Controllers.PackageController.GetRemotePackages()  
```

**Comment by david-poindexter** [comment]
@WillStrohl that error means nvQuickSite is having trouble connecting with GitHub.  Here is the section of code that handles that.

https://github.com/nvisionative/nvQuickSite/blob/develop/nvQuickSite/Controllers/PackageController.cs#L145-L164

I would recommend trying to access the URL (https://raw.githubusercontent.com/nvisionative/nvQuickSite/main/nvQuickSite/data/packages.json) directly via the browser on that workspace and see if it is being blocked somehow.  According to the error log you shared, it was getting a `(404) Not Found` on this line:  

https://github.com/nvisionative/nvQuickSite/blob/develop/nvQuickSite/Controllers/PackageController.cs#L152
