### ISSUE TITLE
Feature Request - for Release Candidates, show some details?

### ISSUE THREAD

**Issue by jeremy-farrance** [nvisionative/nvQuickSite#373]
I am not sure this is possible unless there is something that gets published with DNN's release candidate versioning to make this possible or easy. But currently, when you have Release Candidates showing, you do not get any confirmation as to which version is being downloaded and installed.

![image](https://user-images.githubusercontent.com/653301/217114132-f5308dde-d94b-4c15-b711-0d78816e0bf5.png)
 
In the image above, RC1 had been out for a few days, but RC2 had just dropped a few hours ago and in this case, appeared to have replaced RC1. I do note that the release Tag is `/releases/tag/v9.11.1-rc2` so maybe there is a simple way to surface that info?

**Comment by jeremy-farrance** [comment]
Also, after you've got the site installed and running, where in DNN can I see and confirm that I am running v9.11.01-RC2? 

You know, if I were being suspicious and doubtful the next day and just wasn't sure anymore.

**Comment by david-poindexter** [comment]
> Also, after you've got the site installed and running, where in DNN can I see and confirm that I am running v9.11.01-RC2?
> 
> You know, if I were being suspicious and doubtful the next day and just wasn't sure anymore.

This is outside the purview of nvQuickSite.  😉
