### ISSUE TITLE
ERR_CONNECTION_REFUSED after updating the DNN Platform, is this a bug or a fixable issue? If this problem if fixable how can I fix this issue?

### ISSUE THREAD

**Issue by Diomuzan** [nvisionative/nvQuickSite#379]
Hi everyone, I've installed a older version of the DNN Platform some time ago but since the last update the DNN Platform acts super weird on my laptop. I've installed the DNN Platform with NVQuickSite. I see the error "ERR_CONNECTION_REFUSED" and I can confirm that the Microsoft SQL Server is turned on.

This is what I've tried unsuccessfully:

 - Reinstalling the DNN Platform

- Reinstalling Google Chrome Dev

- Using Google DNS

- Executing the command "Netsh winsock reset"

- Clearing cache of DNS

- Restarting Microsoft SQL Server

- Restarting laptop

- Clearing all browser data of Google Chrome Dev

- Clearing all cache of Google Chrome Dev

- Updating the DNN Platform to the newest version

I want to further add the fact that after I updated the DNN Platform to the latest version and it did in fact worked well for a while but suddenly I see the same error again when I made this issue. Reinstalling the DNN Platform and restarting the laptop didn't helped either this time so I haven't ideas left about how I could possibly solve the issue. 

Is this a bug or a fixable issue and if this is a fixable issue how can I fix this?
![Screenshot 2024-01-30 101712](https://github.com/nvisionative/nvQuickSite/assets/94070451/6ef276a0-d2a9-4d2b-a603-53f6589fc58a)

**Comment by david-poindexter** [comment]
This looks like an SSL related issue.  Is the site you are installing using SSL?  Later versions of nvQuickSite have SSL enabled by default and it will use a development certificate that you select.

**Comment by Diomuzan** [comment]
Hi Mr. Poindexter. thanks for your reaction firstly and secondly I've checked if I got SSL enabled in my project and the SSL is disabled.

**Comment by valadas** [comment]
Ok, my other guess would be a problem writing to the HOSTS file.

Can you check the file c:\Windows\System32\drivers\etc\hosts in vscode or notepad. 

You should have entries like these:
```
	127.0.0.1 	9130.loc
	127.0.0.1 	9131.loc
	127.0.0.1 	9132.loc
	127.0.0.1 	9133.loc
```

But with the domain and extension you have selected in nvQuickSite.
If you don't, many antivirus keep a close eye on that file and you may have to add nvQuickSite to exclusions.

**Comment by david-poindexter** [comment]
> Hi Mr. Poindexter. thanks for your reaction firstly and secondly I've checked if I got SSL enabled in my project and the SSL is disabled.

@Diomuzan by "enabled in my project", are you referring to your IIS site bindings?  If not, please check those to ensure it is or is not setup for SSL.

**Comment by Diomuzan** [comment]
> Ok, my other guess would be a problem writing to the HOSTS file.
> 
> Can you check the file c:\Windows\System32\drivers\etc\hosts in vscode or notepad.
> 
> You should have entries like these:
> 
> ```
> 	127.0.0.1 	9130.loc
> 	127.0.0.1 	9131.loc
> 	127.0.0.1 	9132.loc
> 	127.0.0.1 	9133.loc
> ```
> 
> But with the domain and extension you have selected in nvQuickSite. If you don't, many antivirus keep a close eye on that file and you may have to add nvQuickSite to exclusions.

I've checked the hosts file and the domain name of the project and the IP adres is included which is 127.0.0.1

**Comment by Diomuzan** [comment]
> > Hi Mr. Poindexter. thanks for your reaction firstly and secondly I've checked if I got SSL enabled in my project and the SSL is disabled.
> 
> @Diomuzan by "enabled in my project", are you referring to your IIS site bindings? If not, please check those to ensure it is or is not setup for SSL.

No, I've not checked the checkbox in enable SSL while walking through the steps of installing the DNN Platform in NVQuickSite.

**Comment by Diomuzan** [comment]
> > Hi Mr. Poindexter. thanks for your reaction firstly and secondly I've checked if I got SSL enabled in my project and the SSL is disabled.
> 
> @Diomuzan by "enabled in my project", are you referring to your IIS site bindings? If not, please check those to ensure it is or is not setup for SSL.

I've checked if SSL is enabled in the IIS website in IIS manager and it's disabled.

**Comment by david-poindexter** [comment]
Since SSL is not enabled, can you confirm that you are visiting http://karaka.dnndev.me in the browser instead of https://karaka.dnndev.me?

If so, then can you try to use a domain other than dnndev.me (e.g., karaka.loc) to see if you have the same issue?

**Comment by Diomuzan** [comment]
H

> Since SSL is not enabled, can you confirm that you are visiting http://karaka.dnndev.me in the browser instead of https://karaka.dnndev.me?
> 
> If so, then can you try to use a domain other than dnndev.me (e.g., karaka.loc) to see if you have the same issue?

Hi there. I've checked the full link out and it was http://karaka.dnndev.me and secondly I've reinstalled the DNN Platform on my project again but this time I set the URL of the website to http://karaka.lo/. This time the website worked and I successfully walked throught the installation wizard but to be honest I'm unsure if the problem is solved. For now I'll consider that this issue is solved but if the issue reappears I'll write a reaction here in this issue. I want to thank for your time and support for now lastly!

**Comment by david-poindexter** [comment]
I generally don't recommend the use of `dnndev.me` unless you fully understand the specific nature of this domain.  Due to the way nvQuickSite works (by modifying your Windows HOSTS file), there is really no need for this special `dnndev.me` domain in this context.

Glad it is resolved for you!

**Comment by Diomuzan** [comment]
> I generally don't recommend the use of `dnndev.me` unless you fully understand the specific nature of this domain. Due to the way nvQuickSite works (by modifying your Windows HOSTS file), there is really no need for this special `dnndev.me` domain in this context.
> 
> Glad it is resolved for you!

I didn't knew that but that is then something I learned this time. Thanks for your help, time and support again!

**Comment by david-poindexter** [comment]
My pleasure. 😊

**Comment by Diomuzan** [comment]
Hi there, I've now tried to open my DNN Platform project but now I get the same error again. I really don't understand why I get keeping this error all the time. It worked fine for a few days but now not anymore.

**Comment by david-poindexter** [comment]
When this happens, can you go into IIS and see if the website is stopped?

**Comment by david-poindexter** [comment]
You may also want to check to ensure your IIS has the URL Rewrite module installed.

**Comment by Diomuzan** [comment]
> When this happens, can you go into IIS and see if the website is stopped?

It doesn't seem that the website is stopped when I check out the IIS Manager if I get that error.

**Comment by david-poindexter** [comment]
There are honestly so many things that could result in this (e.g., router issues, DNS issues in general, etc.) that it is hard to point in the right direction.  It doesn't appear to be an nvQuickSite bug, but I am happy to help.  Perhaps you can join a Discord co-coding session with us and we can help troubleshoot?  If you aren't on the DNN Discord server, here's an invitation link: https://discord.com/invite/F8HJJCXM

**Comment by Diomuzan** [comment]
T

> There are honestly so many things that could result in this (e.g., router issues, DNS issues in general, etc.) that it is hard to point in the right direction. It doesn't appear to be an nvQuickSite bug, but I am happy to help. Perhaps you can join a Discord co-coding session with us and we can help troubleshoot? If you aren't on the DNN Discord server, here's an invitation link: https://discord.com/invite/F8HJJCXM

Hi, thanks firstly for sharing the link to the Discord server of the DNN Platform. A co-coding session could be possible but the time difference will be posing a huge challenge plus the fact that I would not have much time for a co-coding session if I consider the time difference and the the time that I stay at my internship place daily.

**Comment by david-poindexter** [comment]
@Diomuzan the DNN Community is international, so hopefully there will be someone available somewhere to jump on a Discord hangout and help.  I'll post a comment on the Discord forum post you just created today.

**Comment by Diomuzan** [comment]
> @Diomuzan the DNN Community is international, so hopefully there will be someone available somewhere to jump on a Discord hangout and help. I'll post a comment on the Discord forum post you just created today.

Okay, I hope the same
