### ISSUE TITLE
Set Folder Permissions (Unable to continue)

### ISSUE THREAD

**Issue by leedavi** [nvisionative/nvQuickSite#382]
In the past I have had issues with folder permissions.  The issue seemed to be resolved, I have not had a problem for over a year. 

However, the problem is back.  

I have done the usual setup, then I get the "Set Folder Permissions" problem.  Before I was able to ignore, now I cannot continue and the process does not work.

I have tried adding the permission myself and I still get the same error.  It seems to delete the website folder and the permissions I added with it.  

I selected not to delete IIS, in hope this might help. This did not get beyond step 2.  I therefore deleted the IIS website manually and then nvquick had an error.

I rebooted and tried again.  Same error creating IIS.  I removed the AppPool.   Then I get the same error with Folder Permissions.

I had to give up and install manually.

This is on "Microsoft Windows Server 2022 Standard"

**Comment by david-poindexter** [comment]
@leedavi most likely some anti-virus and/or security software is getting in the way.  This is almost always the cause when this issue occurs.  You could try temporarily disabling it to test and rule it out.

**Comment by leedavi** [comment]
Ok, thx I will try that.

**Comment by leedavi** [comment]
This was a new server and I tried to use nvquick before I upgraded windows.  In may have been the background upgrade process locking files.
