### ISSUE TITLE
Determine upgrade strategy

### ISSUE THREAD

**Issue by hismightiness** [nvisionative/nvQuickSite#39]
How does one go from version 1 to version 2?

**Comment by nvisionative** [comment]
We are looking into three different options as this point.

- **Single, stand-alone EXE** (does not "install", just runs in place - like MakeDNNSite) - in this case, they would simply download the latest version EXE.

- Installer (e.g., MSI or EXE) - this would require that an installer solution/package be built and maintained moving forward.  This would provide the ability for various install options, etc.  In this case, the upgrade path would be to just install the next version on top of the old one.

- Web Publishing (of some shape/form/fashion)

Do you have a preference?  Do you think others will have a preference?

**Comment by hismightiness** [comment]
My preference is:  whatever will be the easiest for the people that use DQS

**Comment by nvisionative** [comment]
Which option do you think would be easiest for you?

**Comment by hismightiness** [comment]
A standard experience.  A new version is available.  I download it, and run it.  If there's anything to be upgraded, the upgrade just happens (maybe with a wizard).  No requirement to uninstall, delete, or replace a DLL.

**Comment by nvisionative** [comment]
Gotcha - so an installation experience is not considered an annoyance by you unless of course it requires some crazy "jumping through of hoops".  Thanks!

**Comment by nvisionative** [comment]
An installer has been created (see #18) and it handles the upgrade path by automatically removing the previous version and installing the new version.  If an install attempt is made with the same version or older, a prompt is displayed instructing the user to first uninstall the existing application via Add/Remove Programs.  For now, all releases of the installer will be a single MSI (Windows Installer) file.
