### ISSUE TITLE
Disable next button until fields are validated

### ISSUE THREAD

**Issue by hismightiness** [nvisionative/nvQuickSite#40]
INSTALL PACKAGE INFO
Disable next button until a local package is selected.

If it's clicked, have a tool tip appear to remind the user that they need to choose a package in order to continue.

SITE INFO
Disable next button until Site Name and Location are each populated.

If next is clicked before fields are populated, remind the user about those two fields.

DATABASE INFO
Disable next button until Server Name and Database Name are populated.  If SQL Server Authentication is chosen, then those two fields will be required as well.

If next is clicked before fields are populated, remind the user about the fields.

**Comment by nvisionative** [comment]
Validation currently occurs on the click event handler for the Next buttons.  Disabling the Next button until field values are present would require the use of a TextChanged handler, which can be a bit clunky in WinForms.  We'll try it out and see what happens though.

**Comment by hismightiness** [comment]
I'm mostly identifying a user story.  The "how" is completely up to you.  I know too much to write an actual user story.

**Comment by nvisionative** [comment]
Thanks!

**Comment by nvisionative** [comment]
@hismightiness are you happy with the way this is working now or do you think further refinement is necessary?  It doesn't currently work exactly as the user story depicts, but it does work better than it did at the point this issue was created.  Thanks and we look forward to your feedback!

**Comment by hismightiness** [comment]
I think the current method is fine for now.

**Comment by nvisionative** [comment]
Thanks for the feedback.  We'll go ahead and close this issue.
