### ISSUE TITLE
HOST file entry on same line

### ISSUE THREAD

**Issue by hismightiness** [nvisionative/nvQuickSite#50]
Here's how I did this:

1. Clean install of entire system (new laptop)
2. Installed all development prerequisites (VS, IIS, SQL, etc.)
3. Updated hosts file with a single entry and no new line after
4. Installed DQS
5. Ran DQS with all of the defaults (MySite.local)
6. Attempted to view the site by clicking "Visit Site" at the end of the process

I have a cloud file server in the house, so I already had a single entry in the hosts file, such as:

192.168.1.100          servername

After running DQS for the first time, the hosts file looked like this:

192.168.1.100          servername127.0.0.1          MySite.local

**Comment by nvisionative** [comment]
Re-opening due to the existence of unnecessary blank lines.  Need to detect the existence (or not) of a new line at the end of the file an add the new entry accordingly.
