### ISSUE TITLE
Seemingly random issue with "Set Folder Permissions"

### ISSUE THREAD

**Issue by nvisionative** [nvisionative/nvQuickSite#64]
There is a seemingly random issue during the "Set Folder Permissions" routine that we have yet to be able to pinpoint or reproduce at will.  Here is a screenshot of the error.

![screencapture_14 mar 04 02 12](https://cloud.githubusercontent.com/assets/4568451/13520841/c0e3b35a-e1b1-11e5-97dd-078069a40a51.png)

**Comment by hismightiness** [comment]
FYI - I haven't run into that error yet myself.

**Comment by nvisionative** [comment]
Closing this issue for now, as we have not experienced it again.  We'll re-open later if it rears its ugly head again.  :)

**Comment by nvisionative** [comment]
We are still seeing this issue from time to time, but have not been able to determine the cause.

**Comment by nvisionative** [comment]
See issue #110 for additional info.

**Comment by nvisionative** [comment]
Resolved via PR #145 - thank you @abukres - this was one of the most annoying errors to date and you figured out the resolution!  🥇
