### ISSUE TITLE
Undesired UX when entering an invalid DB server name

### ISSUE THREAD

**Issue by hismightiness** [nvisionative/nvQuickSite#69]
If you have a typo in your SQL server name, it should result in an undesired UX.  Take the example below.  This is clearly not a DB server name.

![2016-03-04_0825](https://cloud.githubusercontent.com/assets/938023/13532922/e35a8cde-e1e2-11e5-946d-64d145352527.png)

It takes a while, but it attempts to find the server, and it even give us a notification that it couldn't find it, which is fine - but our only option is to click OK and we're forwarded to the next step, where the site is installed anyway.

![2016-03-04_0826](https://cloud.githubusercontent.com/assets/938023/13532921/e358b576-e1e2-11e5-82d3-8ea9a05bad9f.png)

Instead of going to the next step, we should have the option to continue or fix the typo first (i.e., OK, or Cancel).  

This is really important, because everything gets changed as a result.  There is no DB created, and now I have to do that AND fix the installer information in DNN.

**Comment by nvisionative** [comment]
Great catch!  We'll look into this.
