### ISSUE TITLE
Opt out statistics reporting during initial install

### ISSUE THREAD

**Issue by hismightiness** [nvisionative/nvQuickSite#7]
Have a place to log and report on the following details.  Ideally, in a public way, where any verified community member can know what the current levels are for the DNN installation base.  

Ideas for data collected/reported on:
- Windows version
- Installed .Net frameworks
- SQL Server version number(s)
- Country of origin where the server/computer lives

There should be box that's default to checked, that allows them to opt out, if they want.

Nothing person or unique to the individual/computer should be gathered (e.g., IP address).  But there should be a GUID unique to that app installation so that the usage can be tracked anonymously.

**Comment by nvisionative** [comment]
We'll need a bit more details on this one.  Do you mind sharing you ideas?  Thanks!

**Comment by hismightiness** [comment]
Have a place to log and report on the following details.  Ideally, in a public way, where any verified community member can know what the current levels are for the DNN installation base.  

Ideas for data collected/reported on:

- Windows version
- Installed .Net frameworks
- SQL Server version number(s)
- Number of sites
- Number of installed modules
- Number of installed themes
- Number of users (per portal too)
- Country of origin where the server/computer lives

There should be box that's default to checked, that allows them to opt out, if they want.

**Comment by nvisionative** [comment]
@hismightiness thanks for your input!  Perhaps we should consider creating a module with a web service for this app to post information to and have the stats displayed on the site.  What do you think?

**Comment by hismightiness** [comment]
I think that's definitely a good idea.

**Comment by nvisionative** [comment]
Initial testing has been completed for integration with [Segment](https://segment.com/).  The test included passing human friendly operating system information to Segment and then sending that information to a web service via Webhooks integration.  We will also be looking into passing stats to Google Analytics via the appropriate integration method.  The code is commented out for now until we determine exactly what data and actions we will be tracking.  Segment seems to be a promising data pass-through solution for now, allowing stats to be sent to multiple systems.

**Comment by nvisionative** [comment]
@hismightiness FYI, we were able to get data passing through Segment to Google Analytics.  We will go ahead and plan to track some basic stats in the next release.
