### ISSUE TITLE
(Not) Empty Directory Issues - Unable to Install

### ISSUE THREAD

**Issue by hismightiness** [nvisionative/nvQuickSite#77]
I ran the latest build using the defaults that were already in place, which included an existing DB and web folder.  

When I clicked next upon choosing a populated folder, I received the alert about the directory not being empty.  This was fine and expected.  I clicked OK to dismiss the alert.

At the next step, I left the defaults from the last site I had it create in IIS and tried to continue.  I got this error.

![2016-03-08_1336](https://cloud.githubusercontent.com/assets/938023/13617403/77ce78c8-e533-11e5-920b-983ab708bf12.png)

I dismissed the error.  When I clicked next again, I received this error.

![2016-03-08_1337](https://cloud.githubusercontent.com/assets/938023/13617405/7ad3217c-e533-11e5-83bc-32fbce6512a7.png)

Then, I'd go into a circular pattern between those two error messages if I tried to continue.  

I deleted the contents of the target installation folder, and I was able to continue as expected.

**Comment by nvisionative** [comment]
Thank you for the detailed account of the issue.  This most likely has something to do with the recently implemented workflow.  We'll take a look into it.

**Comment by hismightiness** [comment]
I doubt this is related, but as an FYI...  the install wizard for this site took an abnormally long period of time to complete.... 3 minutes.  This hasn't happened before on this computer.

**Comment by nvisionative** [comment]
@hismightiness perhaps you were missing a prerequisite for the app and it needed to install it first?

**Comment by hismightiness** [comment]
No, running it again allowed everything to work fine.  I think this is the root cause of the issue...

* The site was previously installed on a different laptop by MakeDNNSite, then moved to this new one and restored
* The site DB was attached from the folder structure, where it lived on this and the previous laptop

Upon further inspection just now, I was able to verify that while it looked like NVQ didn't delete the files/folders in the target folder, it deleted almost everything.  The Logs and Website folder were present, but empty.  However, the Database folder was present and the DB files were still there.

This may be caused by an attached DB being present in the target folder.

**Comment by nvisionative** [comment]
@hismightiness Ah, that helps us understand what may have happened.  Was the database attached in MSSQL Server on the new machine yet?  It sounds like nvQS attempted to delete the database but couldn't find it.

**Comment by nvisionative** [comment]
Upon further investigation, it was determined to be an issue outside of nvQuickSite.  Thanks!
