### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by bhattjidotcom** [nvisionative/nvQuickSite#84]
I am looking at two enhancements

1) One should be able to name the "Application Pool"
2) The entry in the "hosts" file should be optional (at production server, we don't need that entry)

I have download the source but it is not loading (missing two projects)

![nvquicksite_error-loading-projects](https://cloud.githubusercontent.com/assets/10000502/13659098/f9128bf6-e6a3-11e5-80af-49f3efed3111.jpg)

![nvquicksite_not-all-projects](https://cloud.githubusercontent.com/assets/10000502/13658993/7e6716e8-e6a2-11e5-8296-9a8feae7b157.jpg)

**Comment by hismightiness** [comment]
Personally, I don't agree with having a configuration option to name the application pool, or update the Hosts file.  The thing I love about the tool, as it relates to the community in general, is it's simplicity.  We need to make it easier for developers to be involved with DNN, not more difficult.

**Comment by nvisionative** [comment]
@bhattjidotcom thank you for submitting this.  In the future, please report only one issue/suggestion per issue number.

1) We will take this request under consideration.  However, there are several reasons why this may not be a good idea.  The ones @hismightiness has mentioned are definitely important.  Furthermore, the code for removing existing IIS sites depends on a specific naming convention for the AppPool.  Deviating from a naming naming convention would certainly break this important feature of the existing app.

2) The primary use case for this app is for local installations of DNN for testing, development, QA, etc.  it is not currently intended for use on production servers.  A whole new set of considerations would exist for use on production servers (virtualization, etc.).

Regarding the solution/project file issues, we will keep this issue active for those and will report back when resolved.  The other two recommendations will be marked closed for now.

Thanks again for your interest and participation!

**Comment by nvisionative** [comment]
@bhattjidotcom you should now be able to open the solution file and work with it.  Thanks!

**Comment by bhattjidotcom** [comment]
OK,

However, I found that entry in the hosts file is preceded by a tab ("\t") I am sure, you would agree that it needs to be removed

I also wonder, if the same tool can be used to upgrade the existing site. i.e. instead of downloading/selecting the Install package, it should download/select the Upgrade pakage (and of-course, make sure that the site DOES EXISTS)

**Comment by nvisionative** [comment]
@bhattjidotcom **moving forward, please report only one issue/suggestion per issue number**

The tab is there on purpose to improve readability of the HOSTS file.  This is a commonly accepted best practice, but has no actual bearing on the functionality.  It will remain as is.

nvQuickSite is only for install packages at this time.  This would be an interesting feature to explore later on.  Please feel free to open a separate issue to track this enhancement idea.
