### ISSUE TITLE
the Application gives error 

### ISSUE THREAD

**Issue by bhattjidotcom** [nvisionative/nvQuickSite#88]
I downloaded the source code, compiled it, and when I replace the .exe, it gives various errors

What am I doing wrong?

**Comment by nvisionative** [comment]
@bhattjidotcom can you explain what you mean by "replace the .exe"?  You should be able to just run the app from Visual Studio in Debug mode.  Alternatively, you can "Publish" the application from Visual Studio and run from the published directory.
