### ISSUE TITLE
security for database folder

### ISSUE THREAD

**Issue by kingjordan** [nvisionative/nvQuickSite#89]
Hello,

First off, great product and well done!

When I tried to use nvQuicksite to set up a local site I get a permission error at the database stage.  This even happens when I run the program as an administrator.

The errors I get are the following screen captures:
![capture](https://cloud.githubusercontent.com/assets/5931768/13710778/60ffb778-e778-11e5-8edc-984ace736261.PNG)
![capture2](https://cloud.githubusercontent.com/assets/5931768/13710780/644dd3ec-e778-11e5-83e5-0b271b60af17.PNG)

I had to manually change the security access for the folder and then it worked.  Not sure if this just needs to be added to the instructions on how to set up a local site or what?  

Works perfectly once I did this.

Jordan

**Comment by kingjordan** [comment]
sorry, forgot to mention that manually adding full control for the appPool\SiteAppPool and the SqlServerBrowser service did not work.  I added the **everyone ** security role with full access as a quick test and it did work.

**Comment by kingjordan** [comment]
I ran the following query in my sql server to get the name of the service_account
```
SELECT  DSS.servicename,
        DSS.startup_type_desc,
        DSS.status_desc,
        DSS.last_startup_time,
        DSS.service_account,
        DSS.is_clustered,
        DSS.cluster_nodename,
        DSS.filename,
        DSS.startup_type,
        DSS.status,
        DSS.process_id
FROM    sys.dm_server_services AS DSS;
```
I then added that service account as a security role with full access for the local folder and the process continued and created the site, however the first error I linked to in the original post still appears for a brief second before the process continues:
![capture](https://cloud.githubusercontent.com/assets/5931768/13711337/3e669b8e-e77b-11e5-9f16-023d8a383e36.PNG)
Also
once the site appeared none of the images or css files were applied which is another security issue.
I solved this again by adding **everyone**

Anyway, just wanted to report this

**Comment by nvisionative** [comment]
@kingjordan thanks so much for trying out the app and for reporting the issues.  Can you please provide some specs about your local environment (e.g., Operating System, SQL Server, IIS)?

**Comment by hismightiness** [comment]
It might also be useful to have some additional information about the permissions that are set for the parent folder where you're attempting to install this site.  

For example, if the site is installed in C:\\Websites\08.00.00.test2\ ...

What are the permissions for the Websites folder?

**Comment by bhattjidotcom** [comment]
I am also getting the same error
![error installing site](https://cloud.githubusercontent.com/assets/10000502/13777735/d541c41e-ea7f-11e5-851d-bd422d4d2e0f.png)

**Comment by bhattjidotcom** [comment]
Recompiled the Application and replaced the file, then run it. It is giving one more error now
![error reading config file](https://cloud.githubusercontent.com/assets/10000502/13778534/69ac053e-ea84-11e5-9c44-572afce2c015.png)

**Comment by bhattjidotcom** [comment]
I tried the SQL Server Username/Password, instead of "Integrated Security"

I expected that it will ADD that user, but it did not. (I had to use "sa" , that worked though)

**Comment by bhattjidotcom** [comment]
The Log directory was not changed from "%SystemDrive%\inetpub\logs\LogFiles" to "<Location>\Logs" in IIS
![logs directory was not set](https://cloud.githubusercontent.com/assets/10000502/13779729/80de2ac4-ea8a-11e5-859b-f416af55fd12.png)

**Comment by nvisionative** [comment]
@bhattjidotcom and @kingjordan please see [this comment](https://github.com/nvisionative/nvQuickSite/issues/89#issuecomment-195490331) and [this comment](https://github.com/nvisionative/nvQuickSite/issues/89#issuecomment-195496060).  Having this information will help us better understand how to troubleshoot.

Regarding [this comment](https://github.com/nvisionative/nvQuickSite/issues/89#issuecomment-196798635), the first error is the same as posted by @kingjordan.  The second one is due to invalid permissions to the 'master' database.  Using Integrated Security or a username that has permissions to "USE [master]" is required.

Regarding [this comment](https://github.com/nvisionative/nvQuickSite/issues/89#issuecomment-196807277), I again urge you to post only one issue per GitHub issue.  This helps to avoid confusion and also keeps from hijacking someone else's issue.  If you have something more to add to this specific issue, then by all means, chime in and contribute to the conversation.  Otherwise, please [create a new issue](https://github.com/nvisionative/nvQuickSite/issues/new).

Regarding [this comment](https://github.com/nvisionative/nvQuickSite/issues/89#issuecomment-196815405), see above.

Regarding [this comment](https://github.com/nvisionative/nvQuickSite/issues/89#issuecomment-196824935), this is a GREAT observation and should be logged as a separate issue.  Please?  ;-)

**Comment by kingjordan** [comment]
Hello @nvisionative thanks for the follow up and sorry for the delay.

I am using windows 10 pro with sql server developers edition 2014.  this is the only instance I have of sql on this machine and it is a named instance as you can see in the image captures.  I am using IIS 10.0.

@hismightiness the parent folder just has the default permissions for the user / system / adminstartors roles.

I am fine adding everyone as this is a development PC, however I would like to figure out what exact roles are needed.  Maybe this can help someone else

**Comment by nvisionative** [comment]
@kingjordan it looks like you may be doing this within your user directory and perhaps that is where the issue is.  Would you mind testing outside of your user folder?  Once we pin down the issue, we can better handle in the code.  Thanks!

**Comment by kingjordan** [comment]
Exactly! @nvisionative once i used a C:\Websites location for the dnn files everything worked 100% without errors.  I install my sites inside my user folder because of a backup service I have running that captures everything in my user folder

**Comment by nvisionative** [comment]
@kingjordan that makes sense.  Let us do some testing to see what needs to be done differently to handle installations within user folders.  I'm sure it is a permissions related issue.  Thanks for the quick test and feedback!

**Comment by kingjordan** [comment]
no problem, thanks for the great software - i'm willing to help test this issue if you like.

**Comment by nvisionative** [comment]
@kingjordan excellent - we'll let you know as soon as we have a new version to test.  And you are most welcome - we are excited to serve the DNN community in this way!

**Comment by nvisionative** [comment]
Good news!  We have isolated and resolved the issues.  Code will be committed shortly.

**Comment by nvisionative** [comment]
@kingjordan a [new release](https://github.com/nvisionative/nvQuickSite/releases/tag/v1.0.1) was just been published.  Feel free to test and let us know if you experience any issues.

**Comment by kingjordan** [comment]
thanks guys.  I still get the "some or all identity references could not be translated" but after I hit okay the process completes and the site works perfectly when installed inside my user folder.  Great job!

**Comment by nvisionative** [comment]
@kingjordan - you are welcome. We are glad it is working for you now.  This other issue is most likely related to an identity that is not present on some systems.  It seems to be sporadically showing up (most of the time on first-run after nvQuickSite.  Are you consistently seeing the issue?

**Comment by kingjordan** [comment]
so far I have seen it every time I run the program.  I'll let you know if I
can narrow it down more.

jordan

On Mon, Mar 28, 2016 at 11:16 AM, nvisionative <notifications@github.com>
wrote:

> @kingjordan <https://github.com/kingjordan> - you are welcome. We are
> glad it is working for you now. This other issue is most likely related to
> an identity that is not present on some systems. It seems to be
> sporadically showing up (most of the time on first-run after nvQuickSite.
> Are you consistently seeing the issue?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/nvisionative/nvQuickSite/issues/89#issuecomment-202493213>
>



-- 
Jordan King
*KRISIS KONCEPTS*
*Owner / Lead Developer*

jordan@krisis.ca
*WWW.KRISIS.CA <http://WWW.KRISIS.CA>*


*Twitter: KrisisKoncepts <https://twitter.com/KrisisKoncepts>*

*Facebook: KrisisKoncepts <http://www.facebook.com/KrisisKoncepts>*
*Pinterest: KrisisKoncepts <http://www.pinterest.com/KrisisKoncepts/>*

**Comment by nvisionative** [comment]
Very interesting.  We are developing on Windows 10 machines with MSSQL Server 2014 (not Developers Edition though) and are only seeing the error sporadically.  We have re-opened issue #64 so let's continue this discussion there.
