### ISSUE TITLE
"SQL Server User" NOT added

### ISSUE THREAD

**Issue by bhattjidotcom** [nvisionative/nvQuickSite#90]
I tried the SQL Server Username/Password, instead of "Integrated Security"

I expected that it will ADD that user, but it did not. (I had to use "sa" , that worked though)

**Comment by nvisionative** [comment]
@bhattjidotcom thank you for posting this as a separate issue.  Let us give this some thought on how to best handle and we'll circle back to you.

**Comment by bhattjidotcom** [comment]
Hi

I guess, this feature is a needed one :)

If the user is not there, a user with requisite permission may be added
If user exists, but does not have requisite permissions, those permissions may be granted

**Comment by nvisionative** [comment]
@bhattjidotcom - we have determined the app works as designed.  Creation of a database user is outside the scope of this app.  Adding this additional functionality would complicate the UI/UX.  It would require two sets of database credentials/methods to be entered (one for connection to the database to do work and one for DNN).  This will potentially lead to even more scenarios for confusion and troubles.  This is not something we want to do at this time.

**Comment by hismightiness** [comment]
I agree.

**Comment by nvisionative** [comment]
Thanks for the confirmation @hismightiness

**Comment by hismightiness** [comment]
That's what I'm here for. To confirm your direction. You keep doing the important work.  [This is where you might normally see an emoji.]

**Comment by hismightiness** [comment]
Also, I didn't know there were reactions here... I would have just used that instead.  Cool.
