### ISSUE TITLE
Log directory was not changed in IIS

### ISSUE THREAD

**Issue by bhattjidotcom** [nvisionative/nvQuickSite#91]
The Log directory was not changed from "%SystemDrive%\inetpub\logs\LogFiles" to "<Location>\Logs" in IIS
![logs directory was not set](https://cloud.githubusercontent.com/assets/10000502/13779729/80de2ac4-ea8a-11e5-859b-f416af55fd12.png)

**Comment by nvisionative** [comment]
Thank you for reporting this - we will look into it.

**Comment by nvisionative** [comment]
We have resolved this issue and it will be included in the next commit.
