### ISSUE TITLE
Error after recompilation of Source

### ISSUE THREAD

**Issue by bhattjidotcom** [nvisionative/nvQuickSite#92]
Recompiled the Application and replaced the file, then run it. It is giving one more error now
![error reading config file](https://cloud.githubusercontent.com/assets/10000502/13778534/69ac053e-ea84-11e5-9c44-572afce2c015.png)

**Comment by nvisionative** [comment]
Can you please explain what you mean by "replaced the file"?  Also, have you modified the source code?  We have not been able to reproduce this error.

**Comment by bhattjidotcom** [comment]
Yes, I downloaded the source, remove the tab "\t" while posting to Hosts file, and recompiled the source in release mode, then I replaced the .exe file in the Program files folder

**Comment by nvisionative** [comment]
We have been unable to reproduce this error.  I would highly recommend you run in Debug mode and step through the CreateSiteInIIS() method.
