### ISSUE TITLE
Error running for the first time on a new computer

### ISSUE THREAD

**Issue by bhattjidotcom** [nvisionative/nvQuickSite#93]
I am also getting the same error
![error installing site](https://cloud.githubusercontent.com/assets/10000502/13777735/d541c41e-ea7f-11e5-851d-bd422d4d2e0f.png)

Then after, it could not create the DB too
![error creating db](https://cloud.githubusercontent.com/assets/10000502/13777796/24cd78b6-ea80-11e5-837e-81b1162a310d.png)

**Comment by nvisionative** [comment]
These are two different issues.  The first one we believe is being addressed in another issue.  The second one is due to not entering adequate database credentials.
